<template>
  <div class="tab-page">
    <el-form :inline="true" :model="query" size="small" class="filter-form"><el-form-item label="钱包名称"><el-input v-model="query.name" clearable placeholder="请输入钱包名称" /></el-form-item><el-form-item><el-button type="primary" @click="search">筛选</el-button><el-button @click="resetQuery">重置</el-button></el-form-item></el-form>
    <div class="toolbar"><el-button type="success" size="small" @click="openCreate">新增钱包</el-button></div>
    <el-table :data="page.rows" border stripe size="mini"><el-table-column type="index" label="序号" width="60" /><el-table-column prop="name" label="钱包名称" min-width="140" /><el-table-column prop="code" label="钱包code" width="130" /><el-table-column label="钱包场馆" min-width="240"><template slot-scope="s">{{ venueNames(s.row.venueIds) }}</template></el-table-column><el-table-column label="授权数" width="90" align="center"><template slot-scope="s"><el-button type="text" @click="openAuthorizedSites(s.row)">{{ walletAuthCount(s.row) }}</el-button></template></el-table-column><el-table-column label="操作" width="250" fixed="right"><template slot-scope="s"><el-button type="text" size="mini" @click="openEdit(s.row)">编辑</el-button><el-button v-if="!s.row.locked" type="text" size="mini" class="danger" @click="setLock(s.row,true)">锁定钱包</el-button><el-button v-else type="text" size="mini" @click="setLock(s.row,false)">解锁钱包</el-button><el-button type="text" size="mini" class="danger" @click="remove(s.row)">删除</el-button></template></el-table-column></el-table>
    <pagination v-show="page.total>0" :total="page.total" :page.sync="pageNum" :limit.sync="pageSize" @pagination="syncPage" />
    <el-dialog :title="editingId?'编辑钱包':'新增钱包'" :visible.sync="dialogVisible" width="560px" append-to-body><el-form :model="form" label-width="110px" size="small"><el-form-item label="钱包名称" required><el-input v-model.trim="form.name" /></el-form-item><el-form-item label="钱包CODE" required><el-input v-model.trim="form.code" /></el-form-item><el-form-item label="关联场馆" required><el-select v-model="form.venueIds" multiple filterable class="full"><el-option v-for="item in state.venues" :key="item.id" :label="item.nameZh" :value="item.id" /></el-select></el-form-item></el-form><span slot="footer"><el-button @click="dialogVisible=false">取消</el-button><el-button type="primary" @click="submit">提交</el-button></span></el-dialog>
    <el-dialog :title="authorizedSitesTitle" :visible.sync="authorizedSitesVisible" width="560px" append-to-body><el-table v-loading="authorizedSitesLoading" :data="authorizedSiteRows" border stripe size="mini" empty-text="该钱包暂未授权站点"><el-table-column type="index" label="序号" width="70" align="center" /><el-table-column prop="name" label="站点名称" min-width="180" /><el-table-column prop="code" label="站点编号" min-width="150" /></el-table><span slot="footer"><el-button type="primary" @click="authorizedSitesVisible=false">关闭</el-button></span></el-dialog>
  </div>
</template>
<script>
import { listSite } from '@/api/site/site'
const {cloneState,filterWallets,normalizeSiteRows,paginate,validateWallet}=require('./model')
const emptyWallet=()=>({id:null,name:'',code:'',venueIds:[],locked:false,siteStatuses:{'2222':true,SITE001:false,SITE002:false,SITE003:false}})
export default{name:'WalletList',props:{state:{type:Object,required:true}},data(){return{query:{name:''},appliedQuery:{},pageNum:1,pageSize:10,dialogVisible:false,editingId:null,form:emptyWallet(),authorizedSitesVisible:false,authorizedSitesWalletId:null,authorizedSitesLoading:false,authorizedSitesSource:[]}},computed:{page(){return paginate(filterWallets(this.state.wallets,this.appliedQuery),this.pageNum,this.pageSize)},currentAuthorizedSitesWallet(){return this.state.wallets.find(item=>item.id===this.authorizedSitesWalletId)||null},authorizedSitesTitle(){return`已授权站点 - ${this.currentAuthorizedSitesWallet?this.currentAuthorizedSitesWallet.name:''}`},authorizedSiteRows(){const wallet=this.currentAuthorizedSitesWallet;if(!wallet)return[];const sites=new Map(this.authorizedSitesSource.map(site=>[site.code,site]));return Object.keys(wallet.siteStatuses||{}).filter(code=>wallet.siteStatuses[code]).map(code=>sites.get(code)||{code,name:code})}},methods:{search(){this.appliedQuery=cloneState(this.query);this.pageNum=1},resetQuery(){this.query={name:''};this.search()},syncPage({page,limit}){this.pageNum=page;this.pageSize=limit},venueNames(ids){return ids.map(id=>(this.state.venues.find(v=>v.id===id)||{}).nameZh).filter(Boolean).join('、')||'-'},walletAuthCount(row){return Object.values(row.siteStatuses||{}).filter(Boolean).length},async openAuthorizedSites(row){this.authorizedSitesWalletId=row.id;this.authorizedSitesSource=[];this.authorizedSitesVisible=true;this.authorizedSitesLoading=true;try{const response=await listSite({pageNum:1,pageSize:1000});this.authorizedSitesSource=normalizeSiteRows((response&&response.rows)||[])}catch(error){this.$message.error('站点列表获取失败')}finally{this.authorizedSitesLoading=false}},openCreate(){this.editingId=null;this.form=emptyWallet();this.dialogVisible=true},openEdit(row){this.editingId=row.id;this.form=cloneState(row);this.dialogVisible=true},submit(){const r=validateWallet(this.form,this.state.wallets,this.editingId);if(!r.valid)return this.$message.warning(r.message);if(this.editingId)Object.assign(this.state.wallets.find(i=>i.id===this.editingId),cloneState(this.form));else{this.form.id=Math.max(0,...this.state.wallets.map(i=>Number(i.id)))+1;this.state.wallets.unshift(cloneState(this.form))}this.$emit('state-change');this.dialogVisible=false;this.$modal.msgSuccess('钱包保存成功')},setLock(row,value){this.$confirm(`确认${value?'锁定':'解锁'}${row.name}？`,'提示').then(()=>{row.locked=value;this.$emit('state-change');this.$modal.msgSuccess(value?'钱包已锁定':'钱包已解锁')}).catch(()=>{})},remove(row){this.$confirm(`确认删除钱包 ${row.name}？`,'警告',{type:'warning'}).then(()=>{this.state.wallets.splice(this.state.wallets.indexOf(row),1);this.pageNum=this.page.pageNum;this.$emit('state-change');this.$modal.msgSuccess('删除成功')}).catch(()=>{})}}}
</script>
<style scoped>.filter-form{padding-top:10px}.filter-form .el-input,.filter-form .el-select{width:190px}.toolbar{margin-bottom:10px}.full{width:100%}.danger{color:#f56c6c}</style>
