allowBuilds:
  '@parcel/watcher': set this to true or false
  core-js: set this to true or false
  ejs: set this to true or false
  fsevents: set this to true or false
  highlight.js: set this to true or false
