// This file is generated by scripts/generate-role-permission-actions.js.
// It records actual page operations discovered from existing components.
export const generatedComponentActions = {
  "activity/manage/index": [
    {
      "action": "edit",
      "label": "编辑",
      "legacy": ""
    },
    {
      "action": "edit",
      "label": "编辑",
      "legacy": "activity:manage:edit"
    },
    {
      "action": "delete",
      "label": "删除",
      "legacy": ""
    },
    {
      "action": "create",
      "label": "新增",
      "legacy": ""
    },
    {
      "action": "add",
      "label": "新增",
      "legacy": "activity:manage:add"
    }
  ],
  "activity/report/index": [
    {
      "action": "export",
      "label": "导出",
      "legacy": ""
    }
  ],
  "activity/rewardDetail/FirstDepositParticipation": [
    {
      "action": "unlock",
      "label": "解锁",
      "legacy": ""
    }
  ],
  "activity/rewardDetail/index": [
    {
      "action": "export",
      "label": "导出",
      "legacy": ""
    },
    {
      "action": "grant",
      "label": "发放",
      "legacy": ""
    }
  ],
  "agent/advanceRecords/index": [
    {
      "action": "detail",
      "label": "查看详情",
      "legacy": ""
    },
    {
      "action": "export",
      "label": "导出",
      "legacy": ""
    }
  ],
  "agent/comm/grant": [
    {
      "action": "export",
      "label": "导出",
      "legacy": ""
    },
    {
      "action": "grant",
      "label": "发放",
      "legacy": "agent:commission:grant"
    }
  ],
  "agent/comm/index": [
    {
      "action": "edit",
      "label": "编辑",
      "legacy": ""
    },
    {
      "action": "edit",
      "label": "编辑",
      "legacy": "system:commission:edit"
    },
    {
      "action": "config",
      "label": "配置",
      "legacy": ""
    },
    {
      "action": "delete",
      "label": "删除",
      "legacy": ""
    },
    {
      "action": "remove",
      "label": "删除",
      "legacy": "system:commission:remove"
    }
  ],
  "agent/comm/record": [
    {
      "action": "export",
      "label": "导出",
      "legacy": ""
    },
    {
      "action": "export",
      "label": "导出",
      "legacy": "agent:commission:export"
    }
  ],
  "agent/earningBoard/index": [
    {
      "action": "export",
      "label": "导出",
      "legacy": ""
    }
  ],
  "agent/index - 副本": [
    {
      "action": "edit",
      "label": "编辑",
      "legacy": ""
    },
    {
      "action": "edit",
      "label": "编辑",
      "legacy": "member:agent:edit"
    },
    {
      "action": "query",
      "label": "查看",
      "legacy": "member:agent:query"
    },
    {
      "action": "export",
      "label": "导出",
      "legacy": ""
    },
    {
      "action": "export",
      "label": "导出",
      "legacy": "system:agent:export"
    },
    {
      "action": "delete",
      "label": "删除",
      "legacy": ""
    },
    {
      "action": "remove",
      "label": "删除",
      "legacy": "member:agent:remove"
    },
    {
      "action": "create",
      "label": "新增",
      "legacy": ""
    },
    {
      "action": "add",
      "label": "新增",
      "legacy": "member:agent:add"
    }
  ],
  "agent/index": [
    {
      "action": "edit",
      "label": "编辑",
      "legacy": ""
    },
    {
      "action": "edit",
      "label": "编辑",
      "legacy": "member:agent:edit"
    },
    {
      "action": "export",
      "label": "导出",
      "legacy": ""
    },
    {
      "action": "export",
      "label": "导出",
      "legacy": "member:agent:export"
    },
    {
      "action": "create",
      "label": "新增",
      "legacy": ""
    },
    {
      "action": "add",
      "label": "新增",
      "legacy": "member:agent:add"
    },
    {
      "action": "resetPwd",
      "label": "重置密码",
      "legacy": "member:agent:resetPwd"
    }
  ],
  "agent/negativeProfitReport/index": [
    {
      "action": "export",
      "label": "导出",
      "legacy": ""
    },
    {
      "action": "download",
      "label": "下载",
      "legacy": ""
    }
  ],
  "agent/negativeProfitSettlement/index": [
    {
      "action": "edit",
      "label": "编辑",
      "legacy": ""
    },
    {
      "action": "export",
      "label": "导出",
      "legacy": ""
    },
    {
      "action": "grant",
      "label": "发放",
      "legacy": ""
    },
    {
      "action": "download",
      "label": "下载",
      "legacy": ""
    }
  ],
  "agent/reversal/repayment/index": [
    {
      "action": "export",
      "label": "导出",
      "legacy": ""
    },
    {
      "action": "export",
      "label": "导出",
      "legacy": "agent:reversalRepayment:export"
    }
  ],
  "agent/reversal/stats/index": [
    {
      "action": "export",
      "label": "导出",
      "legacy": ""
    },
    {
      "action": "export",
      "label": "导出",
      "legacy": "agent:reversalStats:export"
    }
  ],
  "agent/settlementCycle/index": [
    {
      "action": "edit",
      "label": "编辑",
      "legacy": ""
    },
    {
      "action": "config",
      "label": "配置",
      "legacy": ""
    },
    {
      "action": "delete",
      "label": "删除",
      "legacy": ""
    },
    {
      "action": "create",
      "label": "新增",
      "legacy": ""
    }
  ],
  "backends/siteAdmin/agent/applywithdraw/index": [
    {
      "action": "edit",
      "label": "编辑",
      "legacy": ""
    }
  ],
  "backends/siteAdmin/agent/grant": [
    {
      "action": "export",
      "label": "导出",
      "legacy": ""
    },
    {
      "action": "grant",
      "label": "发放",
      "legacy": "agent:commission:grant"
    }
  ],
  "backends/siteAdmin/agent/index": [
    {
      "action": "edit",
      "label": "编辑",
      "legacy": ""
    },
    {
      "action": "edit",
      "label": "编辑",
      "legacy": "member:agent:edit"
    },
    {
      "action": "create",
      "label": "新增",
      "legacy": ""
    },
    {
      "action": "add",
      "label": "新增",
      "legacy": "member:agent:add"
    },
    {
      "action": "resetPwd",
      "label": "重置密码",
      "legacy": "member:agent:resetPwd"
    }
  ],
  "backends/siteAdmin/agent/record": [
    {
      "action": "export",
      "label": "导出",
      "legacy": ""
    },
    {
      "action": "export",
      "label": "导出",
      "legacy": "agent:commission:export"
    }
  ],
  "backends/siteAdmin/agent/reversal/repayment/index": [
    {
      "action": "export",
      "label": "导出",
      "legacy": ""
    },
    {
      "action": "export",
      "label": "导出",
      "legacy": "agent:reversalRepayment:export"
    }
  ],
  "backends/siteAdmin/agent/reversal/stats/index": [
    {
      "action": "export",
      "label": "导出",
      "legacy": ""
    },
    {
      "action": "export",
      "label": "导出",
      "legacy": "agent:reversalStats:export"
    }
  ],
  "backends/siteAdmin/agent/transferdetail/index": [
    {
      "action": "export",
      "label": "导出",
      "legacy": ""
    }
  ],
  "backends/siteAdmin/agent/venueAgentFeeDetail/index": [
    {
      "action": "export",
      "label": "导出",
      "legacy": ""
    },
    {
      "action": "export",
      "label": "导出",
      "legacy": "venue:agentFeeDetail:export"
    }
  ],
  "backends/siteAdmin/funds/account/adjust": [
    {
      "action": "detail",
      "label": "查看详情",
      "legacy": ""
    }
  ],
  "backends/siteAdmin/funds/account/index": [
    {
      "action": "edit",
      "label": "编辑",
      "legacy": ""
    },
    {
      "action": "edit",
      "label": "编辑",
      "legacy": "system:account:edit"
    },
    {
      "action": "delete",
      "label": "删除",
      "legacy": ""
    },
    {
      "action": "remove",
      "label": "删除",
      "legacy": "system:account:remove"
    },
    {
      "action": "create",
      "label": "新增",
      "legacy": ""
    },
    {
      "action": "add",
      "label": "新增",
      "legacy": "system:account:add"
    }
  ],
  "backends/siteAdmin/funds/adjust/approve": [
    {
      "action": "reject",
      "label": "审核拒绝",
      "legacy": ""
    },
    {
      "action": "approve",
      "label": "审核通过",
      "legacy": ""
    }
  ],
  "backends/siteAdmin/funds/adjust/index": [
    {
      "action": "detail",
      "label": "查看详情",
      "legacy": ""
    }
  ],
  "backends/siteAdmin/funds/center/index": [
    {
      "action": "edit",
      "label": "编辑",
      "legacy": ""
    },
    {
      "action": "detail",
      "label": "查看详情",
      "legacy": ""
    },
    {
      "action": "export",
      "label": "导出",
      "legacy": ""
    }
  ],
  "backends/siteAdmin/funds/redPacket/index": [
    {
      "action": "grant",
      "label": "发放",
      "legacy": ""
    }
  ],
  "backends/siteAdmin/funds/report/index": [
    {
      "action": "export",
      "label": "导出",
      "legacy": ""
    },
    {
      "action": "export",
      "label": "导出",
      "legacy": "game:report:export"
    }
  ],
  "backends/siteAdmin/game/batch/index": [
    {
      "action": "edit",
      "label": "编辑",
      "legacy": ""
    },
    {
      "action": "delete",
      "label": "删除",
      "legacy": ""
    },
    {
      "action": "create",
      "label": "新增",
      "legacy": ""
    }
  ],
  "backends/siteAdmin/game/config/data": [
    {
      "action": "edit",
      "label": "编辑",
      "legacy": ""
    },
    {
      "action": "edit",
      "label": "编辑",
      "legacy": "game:config:edit"
    },
    {
      "action": "delete",
      "label": "删除",
      "legacy": ""
    },
    {
      "action": "remove",
      "label": "删除",
      "legacy": "game:config:remove"
    },
    {
      "action": "create",
      "label": "新增",
      "legacy": ""
    },
    {
      "action": "add",
      "label": "新增",
      "legacy": "game:config:add"
    }
  ],
  "backends/siteAdmin/game/config/index": [
    {
      "action": "edit",
      "label": "编辑",
      "legacy": ""
    },
    {
      "action": "edit",
      "label": "编辑",
      "legacy": "game:config:edit"
    },
    {
      "action": "list",
      "label": "查看",
      "legacy": "game:config:list"
    },
    {
      "action": "config",
      "label": "配置",
      "legacy": ""
    },
    {
      "action": "delete",
      "label": "删除",
      "legacy": ""
    },
    {
      "action": "remove",
      "label": "删除",
      "legacy": "game:config:remove"
    },
    {
      "action": "create",
      "label": "新增",
      "legacy": ""
    },
    {
      "action": "add",
      "label": "新增",
      "legacy": "game:config:add"
    }
  ],
  "backends/siteAdmin/game/index": [
    {
      "action": "edit",
      "label": "编辑",
      "legacy": ""
    },
    {
      "action": "edit",
      "label": "编辑",
      "legacy": "system:game:edit"
    },
    {
      "action": "delete",
      "label": "删除",
      "legacy": ""
    },
    {
      "action": "remove",
      "label": "删除",
      "legacy": "system:game:remove"
    },
    {
      "action": "sync",
      "label": "同步",
      "legacy": ""
    },
    {
      "action": "sync",
      "label": "同步",
      "legacy": "system:game:sync"
    },
    {
      "action": "create",
      "label": "新增",
      "legacy": ""
    },
    {
      "action": "add",
      "label": "新增",
      "legacy": "system:game:add"
    }
  ],
  "backends/siteAdmin/game/record/gameBet": [
    {
      "action": "detail",
      "label": "查看详情",
      "legacy": "system:gameBet:detail"
    },
    {
      "action": "export",
      "label": "导出",
      "legacy": ""
    },
    {
      "action": "export",
      "label": "导出",
      "legacy": "system:gameBet:export"
    }
  ],
  "backends/siteAdmin/game/record/index": [
    {
      "action": "query",
      "label": "查看",
      "legacy": "bet:records:query"
    },
    {
      "action": "export",
      "label": "导出",
      "legacy": ""
    },
    {
      "action": "export",
      "label": "导出",
      "legacy": "bet:records:export"
    },
    {
      "action": "delete",
      "label": "删除",
      "legacy": ""
    },
    {
      "action": "remove",
      "label": "删除",
      "legacy": "bet:records:remove"
    },
    {
      "action": "sync",
      "label": "同步",
      "legacy": ""
    },
    {
      "action": "sync",
      "label": "同步",
      "legacy": "bet:records:sync"
    }
  ],
  "backends/siteAdmin/member/team/index": [
    {
      "action": "edit",
      "label": "编辑",
      "legacy": ""
    },
    {
      "action": "edit",
      "label": "编辑",
      "legacy": "member:team:edit"
    },
    {
      "action": "delete",
      "label": "删除",
      "legacy": ""
    },
    {
      "action": "remove",
      "label": "删除",
      "legacy": "member:team:remove"
    },
    {
      "action": "create",
      "label": "新增",
      "legacy": ""
    },
    {
      "action": "add",
      "label": "新增",
      "legacy": "member:team:add"
    }
  ],
  "backends/siteAdmin/member/user/index": [
    {
      "action": "edit",
      "label": "编辑",
      "legacy": ""
    },
    {
      "action": "edit",
      "label": "编辑",
      "legacy": "member:user:edit"
    },
    {
      "action": "export",
      "label": "导出",
      "legacy": ""
    },
    {
      "action": "delete",
      "label": "删除",
      "legacy": ""
    },
    {
      "action": "remove",
      "label": "删除",
      "legacy": "member:user:remove"
    },
    {
      "action": "create",
      "label": "新增",
      "legacy": ""
    },
    {
      "action": "add",
      "label": "新增",
      "legacy": "member:user:add"
    },
    {
      "action": "resetPwd",
      "label": "重置密码",
      "legacy": ""
    }
  ],
  "backends/siteAdmin/monitor/job/index": [
    {
      "action": "edit",
      "label": "编辑",
      "legacy": ""
    },
    {
      "action": "edit",
      "label": "编辑",
      "legacy": "monitor:job:edit"
    },
    {
      "action": "query",
      "label": "查看",
      "legacy": "monitor:job:query"
    },
    {
      "action": "export",
      "label": "导出",
      "legacy": ""
    },
    {
      "action": "export",
      "label": "导出",
      "legacy": "monitor:job:export"
    },
    {
      "action": "changeStatus",
      "label": "启用/禁用",
      "legacy": "monitor:job:changeStatus"
    },
    {
      "action": "delete",
      "label": "删除",
      "legacy": ""
    },
    {
      "action": "remove",
      "label": "删除",
      "legacy": "monitor:job:remove"
    },
    {
      "action": "create",
      "label": "新增",
      "legacy": ""
    },
    {
      "action": "add",
      "label": "新增",
      "legacy": "monitor:job:add"
    }
  ],
  "backends/siteAdmin/monitor/job/log": [
    {
      "action": "query",
      "label": "查看",
      "legacy": "monitor:job:query"
    },
    {
      "action": "export",
      "label": "导出",
      "legacy": ""
    },
    {
      "action": "export",
      "label": "导出",
      "legacy": "monitor:job:export"
    },
    {
      "action": "delete",
      "label": "删除",
      "legacy": ""
    },
    {
      "action": "remove",
      "label": "删除",
      "legacy": "monitor:job:remove"
    }
  ],
  "backends/siteAdmin/monitor/logininfor/index": [
    {
      "action": "export",
      "label": "导出",
      "legacy": ""
    },
    {
      "action": "export",
      "label": "导出",
      "legacy": "monitor:logininfor:export"
    },
    {
      "action": "unlock",
      "label": "解锁",
      "legacy": ""
    },
    {
      "action": "unlock",
      "label": "解锁",
      "legacy": "monitor:logininfor:unlock"
    },
    {
      "action": "delete",
      "label": "删除",
      "legacy": ""
    },
    {
      "action": "remove",
      "label": "删除",
      "legacy": "monitor:logininfor:remove"
    }
  ],
  "backends/siteAdmin/monitor/online/index": [
    {
      "action": "forceLogout",
      "label": "强制退出",
      "legacy": "monitor:online:forceLogout"
    }
  ],
  "backends/siteAdmin/monitor/operlog/index": [
    {
      "action": "query",
      "label": "查看",
      "legacy": "monitor:operlog:query"
    },
    {
      "action": "export",
      "label": "导出",
      "legacy": ""
    },
    {
      "action": "export",
      "label": "导出",
      "legacy": "monitor:operlog:export"
    },
    {
      "action": "delete",
      "label": "删除",
      "legacy": ""
    },
    {
      "action": "remove",
      "label": "删除",
      "legacy": "monitor:operlog:remove"
    }
  ],
  "backends/siteAdmin/resources/skin/index": [
    {
      "action": "edit",
      "label": "编辑",
      "legacy": ""
    },
    {
      "action": "edit",
      "label": "编辑",
      "legacy": "resources:skin:edit"
    },
    {
      "action": "edit",
      "label": "编辑",
      "legacy": "system:skin:edit"
    },
    {
      "action": "delete",
      "label": "删除",
      "legacy": ""
    },
    {
      "action": "remove",
      "label": "删除",
      "legacy": "resources:skin:remove"
    },
    {
      "action": "remove",
      "label": "删除",
      "legacy": "system:skin:remove"
    },
    {
      "action": "create",
      "label": "新增",
      "legacy": ""
    },
    {
      "action": "add",
      "label": "新增",
      "legacy": "resources:skin:add"
    }
  ],
  "backends/siteAdmin/site/apply": [
    {
      "action": "edit",
      "label": "编辑",
      "legacy": ""
    },
    {
      "action": "edit",
      "label": "编辑",
      "legacy": "game:site:edit"
    },
    {
      "action": "query",
      "label": "查看",
      "legacy": "game:site:query"
    },
    {
      "action": "export",
      "label": "导出",
      "legacy": ""
    },
    {
      "action": "export",
      "label": "导出",
      "legacy": "game:site:export"
    },
    {
      "action": "remove",
      "label": "删除",
      "legacy": "game:site:remove"
    },
    {
      "action": "apply",
      "label": "申请",
      "legacy": "game:site:apply"
    }
  ],
  "backends/siteAdmin/site/approve": [
    {
      "action": "query",
      "label": "查看",
      "legacy": "game:site:query"
    },
    {
      "action": "export",
      "label": "导出",
      "legacy": ""
    },
    {
      "action": "export",
      "label": "导出",
      "legacy": "game:site:export"
    },
    {
      "action": "reject",
      "label": "审核拒绝",
      "legacy": ""
    },
    {
      "action": "approve",
      "label": "审核通过",
      "legacy": ""
    },
    {
      "action": "approve",
      "label": "审核通过",
      "legacy": "game:site:approve"
    }
  ],
  "backends/siteAdmin/site/config/DomainConfig": [
    {
      "action": "edit",
      "label": "编辑",
      "legacy": ""
    },
    {
      "action": "delete",
      "label": "删除",
      "legacy": ""
    },
    {
      "action": "create",
      "label": "新增",
      "legacy": ""
    }
  ],
  "backends/siteAdmin/site/config/GameConfig": [
    {
      "action": "edit",
      "label": "编辑",
      "legacy": ""
    },
    {
      "action": "delete",
      "label": "删除",
      "legacy": ""
    }
  ],
  "backends/siteAdmin/site/config/ResourceConfig": [
    {
      "action": "edit",
      "label": "编辑",
      "legacy": ""
    },
    {
      "action": "edit",
      "label": "编辑",
      "legacy": "game:siteResource:edit"
    },
    {
      "action": "delete",
      "label": "删除",
      "legacy": ""
    },
    {
      "action": "remove",
      "label": "删除",
      "legacy": "game:siteResource:remove"
    },
    {
      "action": "create",
      "label": "新增",
      "legacy": ""
    },
    {
      "action": "add",
      "label": "新增",
      "legacy": "game:siteResource:add"
    }
  ],
  "backends/siteAdmin/site/config/UpdateConfig": [
    {
      "action": "edit",
      "label": "编辑",
      "legacy": ""
    },
    {
      "action": "config",
      "label": "配置",
      "legacy": ""
    },
    {
      "action": "delete",
      "label": "删除",
      "legacy": ""
    },
    {
      "action": "create",
      "label": "新增",
      "legacy": ""
    }
  ],
  "backends/siteAdmin/site/config/VenueConfig": [
    {
      "action": "edit",
      "label": "编辑",
      "legacy": ""
    }
  ],
  "backends/siteAdmin/site/index": [
    {
      "action": "edit",
      "label": "编辑",
      "legacy": ""
    },
    {
      "action": "edit",
      "label": "编辑",
      "legacy": "game:site:edit"
    },
    {
      "action": "export",
      "label": "导出",
      "legacy": ""
    },
    {
      "action": "export",
      "label": "导出",
      "legacy": "game:site:export"
    },
    {
      "action": "config",
      "label": "配置",
      "legacy": ""
    },
    {
      "action": "config",
      "label": "配置",
      "legacy": "game:site:config"
    },
    {
      "action": "delete",
      "label": "删除",
      "legacy": ""
    },
    {
      "action": "remove",
      "label": "删除",
      "legacy": "game:site:remove"
    },
    {
      "action": "apply",
      "label": "申请",
      "legacy": "game:site:apply"
    },
    {
      "action": "approve",
      "label": "审核通过",
      "legacy": "game:site:approve"
    },
    {
      "action": "create",
      "label": "新增",
      "legacy": ""
    },
    {
      "action": "add",
      "label": "新增",
      "legacy": "game:site:add"
    }
  ],
  "backends/siteAdmin/site/resource": [
    {
      "action": "edit",
      "label": "编辑",
      "legacy": ""
    },
    {
      "action": "edit",
      "label": "编辑",
      "legacy": "game:siteResource:edit"
    },
    {
      "action": "delete",
      "label": "删除",
      "legacy": ""
    },
    {
      "action": "remove",
      "label": "删除",
      "legacy": "game:siteResource:remove"
    },
    {
      "action": "create",
      "label": "新增",
      "legacy": ""
    },
    {
      "action": "add",
      "label": "新增",
      "legacy": "game:siteResource:add"
    }
  ],
  "backends/siteAdmin/site/update/index": [
    {
      "action": "edit",
      "label": "编辑",
      "legacy": ""
    },
    {
      "action": "config",
      "label": "配置",
      "legacy": ""
    },
    {
      "action": "delete",
      "label": "删除",
      "legacy": ""
    },
    {
      "action": "create",
      "label": "新增",
      "legacy": ""
    }
  ],
  "backends/siteAdmin/site/update": [
    {
      "action": "edit",
      "label": "编辑",
      "legacy": ""
    },
    {
      "action": "config",
      "label": "配置",
      "legacy": ""
    },
    {
      "action": "delete",
      "label": "删除",
      "legacy": ""
    },
    {
      "action": "create",
      "label": "新增",
      "legacy": ""
    }
  ],
  "backends/siteAdmin/site/venue/GameManage": [
    {
      "action": "edit",
      "label": "编辑",
      "legacy": ""
    },
    {
      "action": "export",
      "label": "导出",
      "legacy": ""
    }
  ],
  "backends/siteAdmin/site/venue/VenueManage": [
    {
      "action": "edit",
      "label": "编辑",
      "legacy": ""
    },
    {
      "action": "export",
      "label": "导出",
      "legacy": ""
    }
  ],
  "backends/siteAdmin/system/config/index": [
    {
      "action": "edit",
      "label": "编辑",
      "legacy": ""
    },
    {
      "action": "edit",
      "label": "编辑",
      "legacy": "system:config:edit"
    },
    {
      "action": "export",
      "label": "导出",
      "legacy": ""
    },
    {
      "action": "export",
      "label": "导出",
      "legacy": "system:config:export"
    },
    {
      "action": "delete",
      "label": "删除",
      "legacy": ""
    },
    {
      "action": "remove",
      "label": "删除",
      "legacy": "system:config:remove"
    },
    {
      "action": "create",
      "label": "新增",
      "legacy": ""
    },
    {
      "action": "add",
      "label": "新增",
      "legacy": "system:config:add"
    }
  ],
  "backends/siteAdmin/system/dept/index": [
    {
      "action": "edit",
      "label": "编辑",
      "legacy": ""
    },
    {
      "action": "edit",
      "label": "编辑",
      "legacy": "system:dept:edit"
    },
    {
      "action": "delete",
      "label": "删除",
      "legacy": ""
    },
    {
      "action": "remove",
      "label": "删除",
      "legacy": "system:dept:remove"
    },
    {
      "action": "create",
      "label": "新增",
      "legacy": ""
    },
    {
      "action": "add",
      "label": "新增",
      "legacy": "system:dept:add"
    }
  ],
  "backends/siteAdmin/system/dict/data": [
    {
      "action": "edit",
      "label": "编辑",
      "legacy": ""
    },
    {
      "action": "edit",
      "label": "编辑",
      "legacy": "system:dict:edit"
    },
    {
      "action": "export",
      "label": "导出",
      "legacy": ""
    },
    {
      "action": "export",
      "label": "导出",
      "legacy": "system:dict:export"
    },
    {
      "action": "delete",
      "label": "删除",
      "legacy": ""
    },
    {
      "action": "remove",
      "label": "删除",
      "legacy": "system:dict:remove"
    },
    {
      "action": "create",
      "label": "新增",
      "legacy": ""
    },
    {
      "action": "add",
      "label": "新增",
      "legacy": "system:dict:add"
    }
  ],
  "backends/siteAdmin/system/dict/index": [
    {
      "action": "edit",
      "label": "编辑",
      "legacy": ""
    },
    {
      "action": "edit",
      "label": "编辑",
      "legacy": "system:dict:edit"
    },
    {
      "action": "export",
      "label": "导出",
      "legacy": ""
    },
    {
      "action": "export",
      "label": "导出",
      "legacy": "system:dict:export"
    },
    {
      "action": "delete",
      "label": "删除",
      "legacy": ""
    },
    {
      "action": "remove",
      "label": "删除",
      "legacy": "system:dict:remove"
    },
    {
      "action": "create",
      "label": "新增",
      "legacy": ""
    },
    {
      "action": "add",
      "label": "新增",
      "legacy": "system:dict:add"
    }
  ],
  "backends/siteAdmin/system/menu/index": [
    {
      "action": "edit",
      "label": "编辑",
      "legacy": ""
    },
    {
      "action": "edit",
      "label": "编辑",
      "legacy": "system:menu:edit"
    },
    {
      "action": "list",
      "label": "查看",
      "legacy": "system:user:list"
    },
    {
      "action": "delete",
      "label": "删除",
      "legacy": ""
    },
    {
      "action": "remove",
      "label": "删除",
      "legacy": "system:menu:remove"
    },
    {
      "action": "create",
      "label": "新增",
      "legacy": ""
    },
    {
      "action": "add",
      "label": "新增",
      "legacy": "system:menu:add"
    }
  ],
  "backends/siteAdmin/system/notice/index": [
    {
      "action": "edit",
      "label": "编辑",
      "legacy": ""
    },
    {
      "action": "edit",
      "label": "编辑",
      "legacy": "system:notice:edit"
    },
    {
      "action": "delete",
      "label": "删除",
      "legacy": ""
    },
    {
      "action": "remove",
      "label": "删除",
      "legacy": "system:notice:remove"
    },
    {
      "action": "create",
      "label": "新增",
      "legacy": ""
    },
    {
      "action": "add",
      "label": "新增",
      "legacy": "system:notice:add"
    }
  ],
  "backends/siteAdmin/system/post/index": [
    {
      "action": "edit",
      "label": "编辑",
      "legacy": ""
    },
    {
      "action": "edit",
      "label": "编辑",
      "legacy": "system:post:edit"
    },
    {
      "action": "export",
      "label": "导出",
      "legacy": ""
    },
    {
      "action": "export",
      "label": "导出",
      "legacy": "system:post:export"
    },
    {
      "action": "delete",
      "label": "删除",
      "legacy": ""
    },
    {
      "action": "remove",
      "label": "删除",
      "legacy": "system:post:remove"
    },
    {
      "action": "create",
      "label": "新增",
      "legacy": ""
    },
    {
      "action": "add",
      "label": "新增",
      "legacy": "system:post:add"
    }
  ],
  "backends/siteAdmin/system/role/authUser": [
    {
      "action": "remove",
      "label": "删除",
      "legacy": "system:role:remove"
    },
    {
      "action": "add",
      "label": "新增",
      "legacy": "system:role:add"
    }
  ],
  "backends/siteAdmin/system/role/index": [
    {
      "action": "edit",
      "label": "编辑",
      "legacy": ""
    },
    {
      "action": "edit",
      "label": "编辑",
      "legacy": "system:role:edit"
    },
    {
      "action": "export",
      "label": "导出",
      "legacy": ""
    },
    {
      "action": "export",
      "label": "导出",
      "legacy": "system:role:export"
    },
    {
      "action": "assign",
      "label": "分配",
      "legacy": ""
    },
    {
      "action": "delete",
      "label": "删除",
      "legacy": ""
    },
    {
      "action": "remove",
      "label": "删除",
      "legacy": "system:role:remove"
    },
    {
      "action": "create",
      "label": "新增",
      "legacy": ""
    },
    {
      "action": "add",
      "label": "新增",
      "legacy": "system:role:add"
    }
  ],
  "backends/siteAdmin/system/user/index": [
    {
      "action": "edit",
      "label": "编辑",
      "legacy": ""
    },
    {
      "action": "edit",
      "label": "编辑",
      "legacy": "system:config:edit"
    },
    {
      "action": "edit",
      "label": "编辑",
      "legacy": "system:user:edit"
    },
    {
      "action": "export",
      "label": "导出",
      "legacy": ""
    },
    {
      "action": "export",
      "label": "导出",
      "legacy": "system:user:export"
    },
    {
      "action": "import",
      "label": "导入",
      "legacy": ""
    },
    {
      "action": "import",
      "label": "导入",
      "legacy": "system:user:import"
    },
    {
      "action": "googleAuth",
      "label": "谷歌验证",
      "legacy": "system:user:googleAuth"
    },
    {
      "action": "delete",
      "label": "删除",
      "legacy": ""
    },
    {
      "action": "remove",
      "label": "删除",
      "legacy": "system:user:remove"
    },
    {
      "action": "add",
      "label": "新增",
      "legacy": "system:user:add"
    },
    {
      "action": "resetPwd",
      "label": "重置密码",
      "legacy": "system:user:resetPwd"
    }
  ],
  "backends/siteAdmin/tool/build/index": [
    {
      "action": "export",
      "label": "导出",
      "legacy": ""
    }
  ],
  "backends/siteAdmin/tool/gen/index": [
    {
      "action": "edit",
      "label": "编辑",
      "legacy": ""
    },
    {
      "action": "edit",
      "label": "编辑",
      "legacy": "tool:gen:edit"
    },
    {
      "action": "import",
      "label": "导入",
      "legacy": ""
    },
    {
      "action": "import",
      "label": "导入",
      "legacy": "tool:gen:import"
    },
    {
      "action": "delete",
      "label": "删除",
      "legacy": ""
    },
    {
      "action": "remove",
      "label": "删除",
      "legacy": "tool:gen:remove"
    },
    {
      "action": "code",
      "label": "生成代码",
      "legacy": "tool:gen:code"
    },
    {
      "action": "sync",
      "label": "同步",
      "legacy": ""
    },
    {
      "action": "preview",
      "label": "预览",
      "legacy": "tool:gen:preview"
    }
  ],
  "backends/siteAdmin/venue/index": [
    {
      "action": "edit",
      "label": "编辑",
      "legacy": ""
    },
    {
      "action": "edit",
      "label": "编辑",
      "legacy": "system:venue:edit"
    },
    {
      "action": "delete",
      "label": "删除",
      "legacy": ""
    },
    {
      "action": "remove",
      "label": "删除",
      "legacy": "system:venue:remove"
    },
    {
      "action": "create",
      "label": "新增",
      "legacy": ""
    },
    {
      "action": "add",
      "label": "新增",
      "legacy": "system:venue:add"
    }
  ],
  "depositWithdrawFee/detail/index": [
    {
      "action": "export",
      "label": "导出",
      "legacy": ""
    }
  ],
  "depositWithdrawFee/report/index": [
    {
      "action": "export",
      "label": "导出",
      "legacy": ""
    },
    {
      "action": "export",
      "label": "导出",
      "legacy": "depositWithdrawFee:report:export"
    }
  ],
  "depositWithdrawFee/setting/index": [
    {
      "action": "save",
      "label": "保存",
      "legacy": "depositWithdrawFee:setting:save"
    },
    {
      "action": "edit",
      "label": "编辑",
      "legacy": "depositWithdrawFee:template:edit"
    },
    {
      "action": "config",
      "label": "配置",
      "legacy": ""
    },
    {
      "action": "delete",
      "label": "删除",
      "legacy": ""
    },
    {
      "action": "remove",
      "label": "删除",
      "legacy": "depositWithdrawFee:template:remove"
    },
    {
      "action": "create",
      "label": "新增",
      "legacy": ""
    },
    {
      "action": "add",
      "label": "新增",
      "legacy": "depositWithdrawFee:template:add"
    }
  ],
  "funds/account/index": [
    {
      "action": "edit",
      "label": "编辑",
      "legacy": ""
    },
    {
      "action": "edit",
      "label": "编辑",
      "legacy": "system:account:edit"
    },
    {
      "action": "delete",
      "label": "删除",
      "legacy": ""
    },
    {
      "action": "remove",
      "label": "删除",
      "legacy": "system:account:remove"
    },
    {
      "action": "create",
      "label": "新增",
      "legacy": ""
    },
    {
      "action": "add",
      "label": "新增",
      "legacy": "system:account:add"
    }
  ],
  "funds/center/index": [
    {
      "action": "detail",
      "label": "查看详情",
      "legacy": ""
    },
    {
      "action": "export",
      "label": "导出",
      "legacy": ""
    }
  ],
  "funds/deposit/index": [
    {
      "action": "remark",
      "label": "备注",
      "legacy": "funds:deposit:remark"
    },
    {
      "action": "query",
      "label": "查看",
      "legacy": "funds:deposit:query"
    },
    {
      "action": "reject",
      "label": "审核拒绝",
      "legacy": "funds:deposit:reject"
    },
    {
      "action": "approve",
      "label": "审核通过",
      "legacy": "funds:deposit:approve"
    },
    {
      "action": "sync",
      "label": "同步",
      "legacy": ""
    },
    {
      "action": "create",
      "label": "新增",
      "legacy": ""
    },
    {
      "action": "add",
      "label": "新增",
      "legacy": "funds:deposit:add"
    }
  ],
  "funds/mainBalance/index": [
    {
      "action": "recharge",
      "label": "补充额度",
      "legacy": "funds:mainBalance:recharge"
    },
    {
      "action": "export",
      "label": "导出",
      "legacy": ""
    },
    {
      "action": "export",
      "label": "导出",
      "legacy": "funds:mainBalance:export"
    },
    {
      "action": "import",
      "label": "导入",
      "legacy": ""
    },
    {
      "action": "activityCash",
      "label": "发活动彩金",
      "legacy": "funds:mainBalance:activityCash"
    },
    {
      "action": "delete",
      "label": "删除",
      "legacy": ""
    },
    {
      "action": "download",
      "label": "下载",
      "legacy": ""
    },
    {
      "action": "add",
      "label": "新增",
      "legacy": "funds:redpacket:add"
    }
  ],
  "funds/nexusAddress/index": [
    {
      "action": "edit",
      "label": "编辑",
      "legacy": "funds:nexusAddress:edit"
    },
    {
      "action": "query",
      "label": "查看",
      "legacy": "funds:nexusAddress:query"
    },
    {
      "action": "import",
      "label": "导入",
      "legacy": ""
    },
    {
      "action": "import",
      "label": "导入",
      "legacy": "funds:nexusAddress:import"
    },
    {
      "action": "status",
      "label": "启用/禁用",
      "legacy": ""
    },
    {
      "action": "delete",
      "label": "删除",
      "legacy": ""
    },
    {
      "action": "remove",
      "label": "删除",
      "legacy": "funds:nexusAddress:remove"
    },
    {
      "action": "release",
      "label": "释放",
      "legacy": "funds:nexusAddress:release"
    }
  ],
  "funds/operationExpense/index": [
    {
      "action": "edit",
      "label": "编辑",
      "legacy": "funds:operationExpense:edit"
    }
  ],
  "funds/pay/payChannel": [
    {
      "action": "edit",
      "label": "编辑",
      "legacy": ""
    },
    {
      "action": "delete",
      "label": "删除",
      "legacy": ""
    },
    {
      "action": "create",
      "label": "新增",
      "legacy": ""
    },
    {
      "action": "v3",
      "label": "v3",
      "legacy": "master-admin-prototype:pay-channel-settings:v3"
    }
  ],
  "funds/pay/withdrawChannel": [
    {
      "action": "edit",
      "label": "编辑",
      "legacy": ""
    },
    {
      "action": "delete",
      "label": "删除",
      "legacy": ""
    },
    {
      "action": "create",
      "label": "新增",
      "legacy": ""
    },
    {
      "action": "v2",
      "label": "v2",
      "legacy": "master-admin-prototype:withdraw-channel-settings:v2"
    }
  ],
  "funds/quotaAdjustment/index": [
    {
      "action": "export",
      "label": "导出",
      "legacy": ""
    },
    {
      "action": "export",
      "label": "导出",
      "legacy": "funds:quotaAdjustment:export"
    },
    {
      "action": "adjust",
      "label": "调整余额",
      "legacy": "funds:quotaAdjustment:adjust"
    },
    {
      "action": "sync",
      "label": "同步",
      "legacy": ""
    }
  ],
  "funds/record/deposit": [
    {
      "action": "view",
      "label": "查看",
      "legacy": "funds:deposit:view"
    },
    {
      "action": "approve",
      "label": "审核通过",
      "legacy": "funds:deposit:approve"
    }
  ],
  "funds/record/depositWithdrawRecord": [
    {
      "action": "view",
      "label": "查看",
      "legacy": "funds:record:view"
    },
    {
      "action": "export",
      "label": "导出",
      "legacy": "funds:depositWithdrawRecord:export"
    }
  ],
  "funds/record/index": [
    {
      "action": "export",
      "label": "导出",
      "legacy": ""
    },
    {
      "action": "export",
      "label": "导出",
      "legacy": "funds:record:export"
    }
  ],
  "funds/record/withdraw": [
    {
      "action": "view",
      "label": "查看",
      "legacy": "funds:withdraw:view"
    },
    {
      "action": "approve",
      "label": "审核通过",
      "legacy": "funds:withdraw:approve"
    },
    {
      "action": "complete",
      "label": "完成",
      "legacy": "funds:withdraw:complete"
    },
    {
      "action": "transfer",
      "label": "转账",
      "legacy": "funds:withdraw:transfer"
    }
  ],
  "funds/redPacketRecord/YuebaoInterestLedger": [
    {
      "action": "export",
      "label": "导出",
      "legacy": ""
    },
    {
      "action": "config",
      "label": "配置",
      "legacy": ""
    },
    {
      "action": "download",
      "label": "下载",
      "legacy": ""
    },
    {
      "action": "ss",
      "label": "ss",
      "legacy": "HH:mm:ss"
    }
  ],
  "funds/redPacketRecord/index": [
    {
      "action": "edit",
      "label": "编辑",
      "legacy": "funds:redpacket:edit"
    },
    {
      "action": "export",
      "label": "导出",
      "legacy": ""
    },
    {
      "action": "export",
      "label": "导出",
      "legacy": "funds:redpacket:export"
    },
    {
      "action": "grant",
      "label": "发放",
      "legacy": ""
    },
    {
      "action": "add",
      "label": "新增",
      "legacy": "funds:redpacket:add"
    }
  ],
  "funds/siteMonthlySettlement/index": [
    {
      "action": "export",
      "label": "导出",
      "legacy": ""
    }
  ],
  "funds/turnover/index": [
    {
      "action": "edit",
      "label": "编辑",
      "legacy": "turnover:config:edit"
    },
    {
      "action": "edit",
      "label": "编辑",
      "legacy": "turnover:withdraw:edit"
    },
    {
      "action": "config",
      "label": "配置",
      "legacy": ""
    }
  ],
  "funds/withdraw/index": [
    {
      "action": "freeze",
      "label": "冻结",
      "legacy": ""
    },
    {
      "action": "reject",
      "label": "审核拒绝",
      "legacy": ""
    },
    {
      "action": "approve",
      "label": "审核通过",
      "legacy": ""
    },
    {
      "action": "approve",
      "label": "审核通过",
      "legacy": "funds:withdraw:approve"
    }
  ],
  "game/batch/index": [
    {
      "action": "edit",
      "label": "编辑",
      "legacy": ""
    },
    {
      "action": "delete",
      "label": "删除",
      "legacy": ""
    },
    {
      "action": "create",
      "label": "新增",
      "legacy": ""
    }
  ],
  "game/config/data": [
    {
      "action": "edit",
      "label": "编辑",
      "legacy": ""
    },
    {
      "action": "edit",
      "label": "编辑",
      "legacy": "game:config:edit"
    },
    {
      "action": "delete",
      "label": "删除",
      "legacy": ""
    },
    {
      "action": "remove",
      "label": "删除",
      "legacy": "game:config:remove"
    },
    {
      "action": "create",
      "label": "新增",
      "legacy": ""
    },
    {
      "action": "add",
      "label": "新增",
      "legacy": "game:config:add"
    }
  ],
  "game/config/index": [
    {
      "action": "edit",
      "label": "编辑",
      "legacy": ""
    },
    {
      "action": "edit",
      "label": "编辑",
      "legacy": "game:config:edit"
    },
    {
      "action": "list",
      "label": "查看",
      "legacy": "game:config:list"
    },
    {
      "action": "config",
      "label": "配置",
      "legacy": ""
    },
    {
      "action": "delete",
      "label": "删除",
      "legacy": ""
    },
    {
      "action": "remove",
      "label": "删除",
      "legacy": "game:config:remove"
    },
    {
      "action": "create",
      "label": "新增",
      "legacy": ""
    },
    {
      "action": "add",
      "label": "新增",
      "legacy": "game:config:add"
    }
  ],
  "game/index": [
    {
      "action": "edit",
      "label": "编辑",
      "legacy": ""
    },
    {
      "action": "edit",
      "label": "编辑",
      "legacy": "system:game:edit"
    },
    {
      "action": "delete",
      "label": "删除",
      "legacy": ""
    },
    {
      "action": "remove",
      "label": "删除",
      "legacy": "system:game:remove"
    },
    {
      "action": "sync",
      "label": "同步",
      "legacy": ""
    },
    {
      "action": "sync",
      "label": "同步",
      "legacy": "system:game:sync"
    },
    {
      "action": "create",
      "label": "新增",
      "legacy": ""
    },
    {
      "action": "add",
      "label": "新增",
      "legacy": "system:game:add"
    }
  ],
  "game/record/gameBet": [
    {
      "action": "detail",
      "label": "查看详情",
      "legacy": "system:gameBet:detail"
    },
    {
      "action": "export",
      "label": "导出",
      "legacy": ""
    },
    {
      "action": "export",
      "label": "导出",
      "legacy": "system:gameBet:export"
    }
  ],
  "game/record/index": [
    {
      "action": "query",
      "label": "查看",
      "legacy": "bet:records:query"
    },
    {
      "action": "delete",
      "label": "删除",
      "legacy": ""
    },
    {
      "action": "remove",
      "label": "删除",
      "legacy": "bet:records:remove"
    },
    {
      "action": "sync",
      "label": "同步",
      "legacy": ""
    },
    {
      "action": "sync",
      "label": "同步",
      "legacy": "bet:records:sync"
    }
  ],
  "member/list/index": [
    {
      "action": "edit",
      "label": "编辑",
      "legacy": ""
    }
  ],
  "member/promotion/index": [
    {
      "action": "edit",
      "label": "编辑",
      "legacy": "member:promotion:edit"
    },
    {
      "action": "config",
      "label": "配置",
      "legacy": ""
    },
    {
      "action": "create",
      "label": "新增",
      "legacy": ""
    }
  ],
  "member/realNameReview/index": [
    {
      "action": "edit",
      "label": "编辑",
      "legacy": ""
    }
  ],
  "member/rebate/index": [
    {
      "action": "edit",
      "label": "编辑",
      "legacy": ""
    },
    {
      "action": "edit",
      "label": "编辑",
      "legacy": "module:rebate:edit"
    },
    {
      "action": "delete",
      "label": "删除",
      "legacy": ""
    },
    {
      "action": "remove",
      "label": "删除",
      "legacy": "module:rebate:remove"
    },
    {
      "action": "create",
      "label": "新增",
      "legacy": ""
    },
    {
      "action": "add",
      "label": "新增",
      "legacy": "module:rebate:add"
    }
  ],
  "member/sameIp/index": [
    {
      "action": "query",
      "label": "查看",
      "legacy": "member:sameIp:query"
    }
  ],
  "member/team/index": [
    {
      "action": "edit",
      "label": "编辑",
      "legacy": ""
    },
    {
      "action": "edit",
      "label": "编辑",
      "legacy": "member:team:edit"
    },
    {
      "action": "delete",
      "label": "删除",
      "legacy": ""
    },
    {
      "action": "remove",
      "label": "删除",
      "legacy": "member:team:remove"
    },
    {
      "action": "create",
      "label": "新增",
      "legacy": ""
    },
    {
      "action": "add",
      "label": "新增",
      "legacy": "member:team:add"
    }
  ],
  "member/vip/index": [
    {
      "action": "config",
      "label": "配置",
      "legacy": ""
    },
    {
      "action": "create",
      "label": "新增",
      "legacy": ""
    }
  ],
  "member/withdrawTurnover/index": [
    {
      "action": "export",
      "label": "导出",
      "legacy": ""
    }
  ],
  "message/index": [
    {
      "action": "edit",
      "label": "编辑",
      "legacy": ""
    },
    {
      "action": "edit",
      "label": "编辑",
      "legacy": "system:message:edit"
    },
    {
      "action": "query",
      "label": "查看",
      "legacy": "system:message:query"
    },
    {
      "action": "recall",
      "label": "撤回",
      "legacy": ""
    },
    {
      "action": "recall",
      "label": "撤回",
      "legacy": "system:message:recall"
    },
    {
      "action": "export",
      "label": "导出",
      "legacy": ""
    },
    {
      "action": "export",
      "label": "导出",
      "legacy": "system:message:export"
    },
    {
      "action": "send",
      "label": "发送",
      "legacy": "system:message:send"
    },
    {
      "action": "delete",
      "label": "删除",
      "legacy": ""
    },
    {
      "action": "remove",
      "label": "删除",
      "legacy": "system:message:remove"
    },
    {
      "action": "create",
      "label": "新增",
      "legacy": ""
    },
    {
      "action": "add",
      "label": "新增",
      "legacy": "system:message:add"
    }
  ],
  "monitor/job/index": [
    {
      "action": "edit",
      "label": "编辑",
      "legacy": ""
    },
    {
      "action": "edit",
      "label": "编辑",
      "legacy": "monitor:job:edit"
    },
    {
      "action": "query",
      "label": "查看",
      "legacy": "monitor:job:query"
    },
    {
      "action": "export",
      "label": "导出",
      "legacy": ""
    },
    {
      "action": "export",
      "label": "导出",
      "legacy": "monitor:job:export"
    },
    {
      "action": "changeStatus",
      "label": "启用/禁用",
      "legacy": "monitor:job:changeStatus"
    },
    {
      "action": "delete",
      "label": "删除",
      "legacy": ""
    },
    {
      "action": "remove",
      "label": "删除",
      "legacy": "monitor:job:remove"
    },
    {
      "action": "create",
      "label": "新增",
      "legacy": ""
    },
    {
      "action": "add",
      "label": "新增",
      "legacy": "monitor:job:add"
    }
  ],
  "monitor/job/log": [
    {
      "action": "query",
      "label": "查看",
      "legacy": "monitor:job:query"
    },
    {
      "action": "export",
      "label": "导出",
      "legacy": ""
    },
    {
      "action": "export",
      "label": "导出",
      "legacy": "monitor:job:export"
    },
    {
      "action": "delete",
      "label": "删除",
      "legacy": ""
    },
    {
      "action": "remove",
      "label": "删除",
      "legacy": "monitor:job:remove"
    }
  ],
  "monitor/logininfor/index": [
    {
      "action": "export",
      "label": "导出",
      "legacy": ""
    },
    {
      "action": "export",
      "label": "导出",
      "legacy": "monitor:logininfor:export"
    },
    {
      "action": "unlock",
      "label": "解锁",
      "legacy": ""
    },
    {
      "action": "unlock",
      "label": "解锁",
      "legacy": "monitor:logininfor:unlock"
    },
    {
      "action": "delete",
      "label": "删除",
      "legacy": ""
    },
    {
      "action": "remove",
      "label": "删除",
      "legacy": "monitor:logininfor:remove"
    }
  ],
  "monitor/online/index": [
    {
      "action": "forceLogout",
      "label": "强制退出",
      "legacy": "monitor:online:forceLogout"
    }
  ],
  "monitor/operlog/index": [
    {
      "action": "query",
      "label": "查看",
      "legacy": "monitor:operlog:query"
    },
    {
      "action": "export",
      "label": "导出",
      "legacy": ""
    },
    {
      "action": "export",
      "label": "导出",
      "legacy": "monitor:operlog:export"
    },
    {
      "action": "delete",
      "label": "删除",
      "legacy": ""
    },
    {
      "action": "remove",
      "label": "删除",
      "legacy": "monitor:operlog:remove"
    }
  ],
  "report/agentcommission/index": [
    {
      "action": "export",
      "label": "导出",
      "legacy": ""
    },
    {
      "action": "grant",
      "label": "发放",
      "legacy": ""
    }
  ],
  "report/bonus/index": [
    {
      "action": "export",
      "label": "导出",
      "legacy": ""
    },
    {
      "action": "export",
      "label": "导出",
      "legacy": "vip:bonus:export"
    }
  ],
  "report/dropSignAnalysis/index": [
    {
      "action": "detail",
      "label": "查看详情",
      "legacy": ""
    },
    {
      "action": "export",
      "label": "导出",
      "legacy": ""
    },
    {
      "action": "download",
      "label": "下载",
      "legacy": ""
    },
    {
      "action": "v1",
      "label": "v1",
      "legacy": "master-admin-prototype:drop-sign-node-records:v1"
    },
    {
      "action": "v4",
      "label": "v4",
      "legacy": "master-admin-prototype:drop-sign-analysis:v4"
    }
  ],
  "report/funds/index": [
    {
      "action": "export",
      "label": "导出",
      "legacy": ""
    }
  ],
  "report/marketdata/index": [
    {
      "action": "export",
      "label": "导出",
      "legacy": ""
    }
  ],
  "report/member/index": [
    {
      "action": "export",
      "label": "导出",
      "legacy": ""
    }
  ],
  "report/memberchangerecord/index": [
    {
      "action": "export",
      "label": "导出",
      "legacy": ""
    }
  ],
  "report/memberpromotionstats/index": [
    {
      "action": "export",
      "label": "导出",
      "legacy": ""
    }
  ],
  "report/plat/index": [
    {
      "action": "export",
      "label": "导出",
      "legacy": ""
    }
  ],
  "report/rebate/index": [
    {
      "action": "export",
      "label": "导出",
      "legacy": ""
    },
    {
      "action": "export",
      "label": "导出",
      "legacy": "vip:rebate:export"
    }
  ],
  "report/site/index": [
    {
      "action": "export",
      "label": "导出",
      "legacy": ""
    }
  ],
  "report/siteprofitdetail/index": [
    {
      "action": "export",
      "label": "导出",
      "legacy": ""
    }
  ],
  "report/transferdetail/index": [
    {
      "action": "export",
      "label": "导出",
      "legacy": ""
    }
  ],
  "report/venue/agentFeeDetail/index": [
    {
      "action": "export",
      "label": "导出",
      "legacy": ""
    },
    {
      "action": "export",
      "label": "导出",
      "legacy": "venue:agentFeeDetail:export"
    }
  ],
  "report/venue/feeConfig/index": [
    {
      "action": "edit",
      "label": "编辑",
      "legacy": "venue:feeConfig:edit"
    },
    {
      "action": "config",
      "label": "配置",
      "legacy": ""
    },
    {
      "action": "delete",
      "label": "删除",
      "legacy": ""
    },
    {
      "action": "create",
      "label": "新增",
      "legacy": ""
    }
  ],
  "report/venue/feeDetail/index": [
    {
      "action": "edit",
      "label": "编辑",
      "legacy": "venue:feeDetail:edit"
    },
    {
      "action": "export",
      "label": "导出",
      "legacy": ""
    },
    {
      "action": "export",
      "label": "导出",
      "legacy": "venue:feeDetail:export"
    }
  ],
  "report/venue/index": [
    {
      "action": "export",
      "label": "导出",
      "legacy": ""
    }
  ],
  "report/venueGame/index": [
    {
      "action": "export",
      "label": "导出",
      "legacy": ""
    },
    {
      "action": "download",
      "label": "下载",
      "legacy": ""
    }
  ],
  "report/venueMemberProfit/index": [
    {
      "action": "export",
      "label": "导出",
      "legacy": ""
    },
    {
      "action": "download",
      "label": "下载",
      "legacy": ""
    }
  ],
  "report/venueSummary/index": [
    {
      "action": "export",
      "label": "导出",
      "legacy": ""
    },
    {
      "action": "download",
      "label": "下载",
      "legacy": ""
    }
  ],
  "report/withdrawtransfer/index": [
    {
      "action": "export",
      "label": "导出",
      "legacy": ""
    }
  ],
  "resources/appVersion/index": [
    {
      "action": "edit",
      "label": "编辑",
      "legacy": ""
    },
    {
      "action": "edit",
      "label": "编辑",
      "legacy": "resources:appVersion:edit"
    },
    {
      "action": "config",
      "label": "配置",
      "legacy": ""
    },
    {
      "action": "delete",
      "label": "删除",
      "legacy": ""
    },
    {
      "action": "remove",
      "label": "删除",
      "legacy": "resources:appVersion:remove"
    },
    {
      "action": "upload",
      "label": "上传",
      "legacy": ""
    },
    {
      "action": "download",
      "label": "下载",
      "legacy": ""
    },
    {
      "action": "create",
      "label": "新增",
      "legacy": ""
    },
    {
      "action": "add",
      "label": "新增",
      "legacy": "resources:appVersion:add"
    }
  ],
  "resources/areaCode/index": [
    {
      "action": "edit",
      "label": "编辑",
      "legacy": ""
    },
    {
      "action": "edit",
      "label": "编辑",
      "legacy": "resources:areaCode:edit"
    },
    {
      "action": "delete",
      "label": "删除",
      "legacy": ""
    },
    {
      "action": "remove",
      "label": "删除",
      "legacy": "resources:areaCode:remove"
    },
    {
      "action": "create",
      "label": "新增",
      "legacy": ""
    },
    {
      "action": "add",
      "label": "新增",
      "legacy": "resources:areaCode:add"
    }
  ],
  "resources/gameAutoDisableLog/index": [
    {
      "action": "query",
      "label": "查看",
      "legacy": "resources:gameAutoDisableLog:query"
    },
    {
      "action": "export",
      "label": "导出",
      "legacy": ""
    },
    {
      "action": "export",
      "label": "导出",
      "legacy": "resources:gameAutoDisableLog:export"
    }
  ],
  "resources/gameBase/index": [
    {
      "action": "edit",
      "label": "编辑",
      "legacy": ""
    },
    {
      "action": "edit",
      "label": "编辑",
      "legacy": "resources:gameBase:edit"
    },
    {
      "action": "delete",
      "label": "删除",
      "legacy": ""
    },
    {
      "action": "remove",
      "label": "删除",
      "legacy": "resources:gameBase:remove"
    },
    {
      "action": "create",
      "label": "新增",
      "legacy": ""
    },
    {
      "action": "add",
      "label": "新增",
      "legacy": "resources:gameBase:add"
    }
  ],
  "resources/gameCurrency/index": [
    {
      "action": "edit",
      "label": "编辑",
      "legacy": ""
    },
    {
      "action": "edit",
      "label": "编辑",
      "legacy": "resources:gameCurrency:edit"
    },
    {
      "action": "delete",
      "label": "删除",
      "legacy": ""
    },
    {
      "action": "remove",
      "label": "删除",
      "legacy": "resources:gameCurrency:remove"
    },
    {
      "action": "create",
      "label": "新增",
      "legacy": ""
    },
    {
      "action": "add",
      "label": "新增",
      "legacy": "resources:gameCurrency:add"
    }
  ],
  "resources/gameFactory/index": [
    {
      "action": "edit",
      "label": "编辑",
      "legacy": ""
    },
    {
      "action": "edit",
      "label": "编辑",
      "legacy": "resources:gameFactory:edit"
    },
    {
      "action": "delete",
      "label": "删除",
      "legacy": ""
    },
    {
      "action": "remove",
      "label": "删除",
      "legacy": "resources:gameFactory:remove"
    },
    {
      "action": "create",
      "label": "新增",
      "legacy": ""
    },
    {
      "action": "add",
      "label": "新增",
      "legacy": "resources:gameFactory:add"
    }
  ],
  "resources/gameGroup/index": [
    {
      "action": "bind",
      "label": "绑定",
      "legacy": ""
    },
    {
      "action": "bind",
      "label": "绑定",
      "legacy": "resources:gameGroup:bind"
    },
    {
      "action": "edit",
      "label": "编辑",
      "legacy": ""
    },
    {
      "action": "edit",
      "label": "编辑",
      "legacy": "resources:gameGroup:edit"
    },
    {
      "action": "delete",
      "label": "删除",
      "legacy": ""
    },
    {
      "action": "remove",
      "label": "删除",
      "legacy": "resources:gameGroup:remove"
    },
    {
      "action": "create",
      "label": "新增",
      "legacy": ""
    },
    {
      "action": "add",
      "label": "新增",
      "legacy": "resources:gameGroup:add"
    }
  ],
  "resources/gameLine/index": [
    {
      "action": "edit",
      "label": "编辑",
      "legacy": ""
    },
    {
      "action": "edit",
      "label": "编辑",
      "legacy": "resources:gameLine:edit"
    },
    {
      "action": "delete",
      "label": "删除",
      "legacy": ""
    },
    {
      "action": "remove",
      "label": "删除",
      "legacy": "resources:gameLine:remove"
    },
    {
      "action": "create",
      "label": "新增",
      "legacy": ""
    },
    {
      "action": "add",
      "label": "新增",
      "legacy": "resources:gameLine:add"
    }
  ],
  "resources/realNameChannel/index": [
    {
      "action": "edit",
      "label": "编辑",
      "legacy": ""
    },
    {
      "action": "edit",
      "label": "编辑",
      "legacy": "resources:realNameChannel:edit"
    },
    {
      "action": "delete",
      "label": "删除",
      "legacy": ""
    },
    {
      "action": "remove",
      "label": "删除",
      "legacy": "resources:realNameChannel:remove"
    },
    {
      "action": "create",
      "label": "新增",
      "legacy": ""
    },
    {
      "action": "add",
      "label": "新增",
      "legacy": "resources:realNameChannel:add"
    }
  ],
  "resources/skin/index": [
    {
      "action": "edit",
      "label": "编辑",
      "legacy": ""
    },
    {
      "action": "edit",
      "label": "编辑",
      "legacy": "resources:skin:edit"
    },
    {
      "action": "edit",
      "label": "编辑",
      "legacy": "system:skin:edit"
    },
    {
      "action": "delete",
      "label": "删除",
      "legacy": ""
    },
    {
      "action": "remove",
      "label": "删除",
      "legacy": "resources:skin:remove"
    },
    {
      "action": "remove",
      "label": "删除",
      "legacy": "system:skin:remove"
    },
    {
      "action": "create",
      "label": "新增",
      "legacy": ""
    },
    {
      "action": "add",
      "label": "新增",
      "legacy": "resources:skin:add"
    }
  ],
  "resources/smsChannel/index": [
    {
      "action": "edit",
      "label": "编辑",
      "legacy": ""
    },
    {
      "action": "edit",
      "label": "编辑",
      "legacy": "resources:smsChannel:edit"
    },
    {
      "action": "delete",
      "label": "删除",
      "legacy": ""
    },
    {
      "action": "remove",
      "label": "删除",
      "legacy": "resources:smsChannel:remove"
    },
    {
      "action": "create",
      "label": "新增",
      "legacy": ""
    },
    {
      "action": "add",
      "label": "新增",
      "legacy": "resources:smsChannel:add"
    }
  ],
  "resources/template/index": [
    {
      "action": "edit",
      "label": "编辑",
      "legacy": ""
    },
    {
      "action": "edit",
      "label": "编辑",
      "legacy": "system:messageTemplate:edit"
    },
    {
      "action": "delete",
      "label": "删除",
      "legacy": ""
    },
    {
      "action": "remove",
      "label": "删除",
      "legacy": "system:messageTemplate:remove"
    },
    {
      "action": "auth",
      "label": "授权",
      "legacy": "system:messageTemplate:auth"
    },
    {
      "action": "create",
      "label": "新增",
      "legacy": ""
    },
    {
      "action": "add",
      "label": "新增",
      "legacy": "system:messageTemplate:add"
    }
  ],
  "risk/ipWhitelist/index": [
    {
      "action": "edit",
      "label": "编辑",
      "legacy": ""
    },
    {
      "action": "delete",
      "label": "删除",
      "legacy": ""
    },
    {
      "action": "create",
      "label": "新增",
      "legacy": ""
    }
  ],
  "risk/record/index": [
    {
      "action": "export",
      "label": "导出",
      "legacy": ""
    }
  ],
  "risk/rule/index": [
    {
      "action": "edit",
      "label": "编辑",
      "legacy": ""
    },
    {
      "action": "export",
      "label": "导出",
      "legacy": ""
    },
    {
      "action": "delete",
      "label": "删除",
      "legacy": ""
    },
    {
      "action": "create",
      "label": "新增",
      "legacy": ""
    }
  ],
  "risk/tags/index": [
    {
      "action": "edit",
      "label": "编辑",
      "legacy": ""
    },
    {
      "action": "delete",
      "label": "删除",
      "legacy": ""
    },
    {
      "action": "create",
      "label": "新增",
      "legacy": ""
    }
  ],
  "risk/type/index": [
    {
      "action": "edit",
      "label": "编辑",
      "legacy": ""
    },
    {
      "action": "export",
      "label": "导出",
      "legacy": ""
    },
    {
      "action": "delete",
      "label": "删除",
      "legacy": ""
    },
    {
      "action": "create",
      "label": "新增",
      "legacy": ""
    }
  ],
  "risk/userWhitelist/index": [
    {
      "action": "edit",
      "label": "编辑",
      "legacy": ""
    },
    {
      "action": "delete",
      "label": "删除",
      "legacy": ""
    },
    {
      "action": "create",
      "label": "新增",
      "legacy": ""
    }
  ],
  "site/apply": [
    {
      "action": "edit",
      "label": "编辑",
      "legacy": ""
    },
    {
      "action": "edit",
      "label": "编辑",
      "legacy": "game:site:edit"
    },
    {
      "action": "query",
      "label": "查看",
      "legacy": "game:site:query"
    },
    {
      "action": "export",
      "label": "导出",
      "legacy": ""
    },
    {
      "action": "export",
      "label": "导出",
      "legacy": "game:site:export"
    },
    {
      "action": "remove",
      "label": "删除",
      "legacy": "game:site:remove"
    },
    {
      "action": "apply",
      "label": "申请",
      "legacy": "game:site:apply"
    }
  ],
  "site/approve": [
    {
      "action": "query",
      "label": "查看",
      "legacy": "game:site:query"
    },
    {
      "action": "export",
      "label": "导出",
      "legacy": ""
    },
    {
      "action": "export",
      "label": "导出",
      "legacy": "game:site:export"
    },
    {
      "action": "reject",
      "label": "审核拒绝",
      "legacy": ""
    },
    {
      "action": "approve",
      "label": "审核通过",
      "legacy": ""
    },
    {
      "action": "approve",
      "label": "审核通过",
      "legacy": "game:site:approve"
    }
  ],
  "site/config/ComprehensiveConfig": [
    {
      "action": "edit",
      "label": "编辑",
      "legacy": ""
    },
    {
      "action": "config",
      "label": "配置",
      "legacy": ""
    },
    {
      "action": "delete",
      "label": "删除",
      "legacy": ""
    },
    {
      "action": "create",
      "label": "新增",
      "legacy": ""
    }
  ],
  "site/config/DomainConfig": [
    {
      "action": "edit",
      "label": "编辑",
      "legacy": ""
    },
    {
      "action": "delete",
      "label": "删除",
      "legacy": ""
    },
    {
      "action": "create",
      "label": "新增",
      "legacy": ""
    }
  ],
  "site/config/GameConfig": [
    {
      "action": "edit",
      "label": "编辑",
      "legacy": ""
    },
    {
      "action": "delete",
      "label": "删除",
      "legacy": ""
    }
  ],
  "site/config/ResourceConfig": [
    {
      "action": "edit",
      "label": "编辑",
      "legacy": ""
    },
    {
      "action": "edit",
      "label": "编辑",
      "legacy": "game:siteResource:edit"
    },
    {
      "action": "delete",
      "label": "删除",
      "legacy": ""
    },
    {
      "action": "remove",
      "label": "删除",
      "legacy": "game:siteResource:remove"
    },
    {
      "action": "create",
      "label": "新增",
      "legacy": ""
    },
    {
      "action": "add",
      "label": "新增",
      "legacy": "game:siteResource:add"
    }
  ],
  "site/config/UpdateConfig": [
    {
      "action": "edit",
      "label": "编辑",
      "legacy": ""
    },
    {
      "action": "config",
      "label": "配置",
      "legacy": ""
    },
    {
      "action": "delete",
      "label": "删除",
      "legacy": ""
    },
    {
      "action": "create",
      "label": "新增",
      "legacy": ""
    }
  ],
  "site/config/VenueConfig": [
    {
      "action": "edit",
      "label": "编辑",
      "legacy": ""
    }
  ],
  "site/index": [
    {
      "action": "edit",
      "label": "编辑",
      "legacy": ""
    },
    {
      "action": "edit",
      "label": "编辑",
      "legacy": "game:site:edit"
    },
    {
      "action": "export",
      "label": "导出",
      "legacy": ""
    },
    {
      "action": "export",
      "label": "导出",
      "legacy": "game:site:export"
    },
    {
      "action": "config",
      "label": "配置",
      "legacy": ""
    },
    {
      "action": "config",
      "label": "配置",
      "legacy": "game:site:config"
    },
    {
      "action": "delete",
      "label": "删除",
      "legacy": ""
    },
    {
      "action": "remove",
      "label": "删除",
      "legacy": "game:site:remove"
    },
    {
      "action": "apply",
      "label": "申请",
      "legacy": "game:site:apply"
    },
    {
      "action": "approve",
      "label": "审核通过",
      "legacy": "game:site:approve"
    },
    {
      "action": "create",
      "label": "新增",
      "legacy": ""
    },
    {
      "action": "add",
      "label": "新增",
      "legacy": "game:site:add"
    }
  ],
  "site/launch": [
    {
      "action": "query",
      "label": "查看",
      "legacy": "game:site:publish:query"
    },
    {
      "action": "publish",
      "label": "发布",
      "legacy": ""
    },
    {
      "action": "delete",
      "label": "删除",
      "legacy": ""
    },
    {
      "action": "remove",
      "label": "删除",
      "legacy": "game:site:publish:remove"
    },
    {
      "action": "add",
      "label": "新增",
      "legacy": "game:site:publish:add"
    }
  ],
  "site/resource": [
    {
      "action": "edit",
      "label": "编辑",
      "legacy": ""
    },
    {
      "action": "edit",
      "label": "编辑",
      "legacy": "game:siteResource:edit"
    },
    {
      "action": "delete",
      "label": "删除",
      "legacy": ""
    },
    {
      "action": "remove",
      "label": "删除",
      "legacy": "game:siteResource:remove"
    },
    {
      "action": "create",
      "label": "新增",
      "legacy": ""
    },
    {
      "action": "add",
      "label": "新增",
      "legacy": "game:siteResource:add"
    }
  ],
  "site/venue/GameManage": [
    {
      "action": "edit",
      "label": "编辑",
      "legacy": ""
    },
    {
      "action": "export",
      "label": "导出",
      "legacy": ""
    }
  ],
  "site/venue/VenueManage": [
    {
      "action": "edit",
      "label": "编辑",
      "legacy": ""
    },
    {
      "action": "unlock",
      "label": "解锁",
      "legacy": ""
    },
    {
      "action": "lock",
      "label": "锁定",
      "legacy": ""
    }
  ],
  "system/config/index": [
    {
      "action": "edit",
      "label": "编辑",
      "legacy": ""
    },
    {
      "action": "edit",
      "label": "编辑",
      "legacy": "system:config:edit"
    },
    {
      "action": "export",
      "label": "导出",
      "legacy": ""
    },
    {
      "action": "export",
      "label": "导出",
      "legacy": "system:config:export"
    },
    {
      "action": "delete",
      "label": "删除",
      "legacy": ""
    },
    {
      "action": "remove",
      "label": "删除",
      "legacy": "system:config:remove"
    },
    {
      "action": "create",
      "label": "新增",
      "legacy": ""
    },
    {
      "action": "add",
      "label": "新增",
      "legacy": "system:config:add"
    }
  ],
  "system/dept/index": [
    {
      "action": "edit",
      "label": "编辑",
      "legacy": ""
    },
    {
      "action": "edit",
      "label": "编辑",
      "legacy": "system:dept:edit"
    },
    {
      "action": "delete",
      "label": "删除",
      "legacy": ""
    },
    {
      "action": "remove",
      "label": "删除",
      "legacy": "system:dept:remove"
    },
    {
      "action": "create",
      "label": "新增",
      "legacy": ""
    },
    {
      "action": "add",
      "label": "新增",
      "legacy": "system:dept:add"
    }
  ],
  "system/dict/data": [
    {
      "action": "edit",
      "label": "编辑",
      "legacy": ""
    },
    {
      "action": "edit",
      "label": "编辑",
      "legacy": "system:dict:edit"
    },
    {
      "action": "export",
      "label": "导出",
      "legacy": ""
    },
    {
      "action": "export",
      "label": "导出",
      "legacy": "system:dict:export"
    },
    {
      "action": "delete",
      "label": "删除",
      "legacy": ""
    },
    {
      "action": "remove",
      "label": "删除",
      "legacy": "system:dict:remove"
    },
    {
      "action": "create",
      "label": "新增",
      "legacy": ""
    },
    {
      "action": "add",
      "label": "新增",
      "legacy": "system:dict:add"
    }
  ],
  "system/dict/index": [
    {
      "action": "edit",
      "label": "编辑",
      "legacy": ""
    },
    {
      "action": "edit",
      "label": "编辑",
      "legacy": "system:dict:edit"
    },
    {
      "action": "export",
      "label": "导出",
      "legacy": ""
    },
    {
      "action": "export",
      "label": "导出",
      "legacy": "system:dict:export"
    },
    {
      "action": "delete",
      "label": "删除",
      "legacy": ""
    },
    {
      "action": "remove",
      "label": "删除",
      "legacy": "system:dict:remove"
    },
    {
      "action": "create",
      "label": "新增",
      "legacy": ""
    },
    {
      "action": "add",
      "label": "新增",
      "legacy": "system:dict:add"
    }
  ],
  "system/feedback/index": [
    {
      "action": "edit",
      "label": "编辑",
      "legacy": ""
    },
    {
      "action": "query",
      "label": "查看",
      "legacy": "system:feedback:query"
    },
    {
      "action": "export",
      "label": "导出",
      "legacy": ""
    },
    {
      "action": "export",
      "label": "导出",
      "legacy": "system:feedback:export"
    },
    {
      "action": "config",
      "label": "配置",
      "legacy": ""
    },
    {
      "action": "delete",
      "label": "删除",
      "legacy": ""
    },
    {
      "action": "create",
      "label": "新增",
      "legacy": ""
    },
    {
      "action": "reopen",
      "label": "reopen",
      "legacy": "system:feedback:reopen"
    },
    {
      "action": "reply",
      "label": "reply",
      "legacy": "system:feedback:reply"
    }
  ],
  "system/menu/index": [
    {
      "action": "edit",
      "label": "编辑",
      "legacy": ""
    },
    {
      "action": "edit",
      "label": "编辑",
      "legacy": "system:menu:edit"
    },
    {
      "action": "list",
      "label": "查看",
      "legacy": "system:user:list"
    },
    {
      "action": "delete",
      "label": "删除",
      "legacy": ""
    },
    {
      "action": "remove",
      "label": "删除",
      "legacy": "system:menu:remove"
    },
    {
      "action": "create",
      "label": "新增",
      "legacy": ""
    },
    {
      "action": "add",
      "label": "新增",
      "legacy": "system:menu:add"
    }
  ],
  "system/notice/index": [
    {
      "action": "edit",
      "label": "编辑",
      "legacy": ""
    },
    {
      "action": "edit",
      "label": "编辑",
      "legacy": "system:notice:edit"
    },
    {
      "action": "delete",
      "label": "删除",
      "legacy": ""
    },
    {
      "action": "remove",
      "label": "删除",
      "legacy": "system:notice:remove"
    },
    {
      "action": "create",
      "label": "新增",
      "legacy": ""
    },
    {
      "action": "add",
      "label": "新增",
      "legacy": "system:notice:add"
    }
  ],
  "system/post/index": [
    {
      "action": "edit",
      "label": "编辑",
      "legacy": ""
    },
    {
      "action": "edit",
      "label": "编辑",
      "legacy": "system:post:edit"
    },
    {
      "action": "export",
      "label": "导出",
      "legacy": ""
    },
    {
      "action": "export",
      "label": "导出",
      "legacy": "system:post:export"
    },
    {
      "action": "delete",
      "label": "删除",
      "legacy": ""
    },
    {
      "action": "remove",
      "label": "删除",
      "legacy": "system:post:remove"
    },
    {
      "action": "create",
      "label": "新增",
      "legacy": ""
    },
    {
      "action": "add",
      "label": "新增",
      "legacy": "system:post:add"
    }
  ],
  "system/role/authUser": [
    {
      "action": "remove",
      "label": "删除",
      "legacy": "system:role:remove"
    },
    {
      "action": "add",
      "label": "新增",
      "legacy": "system:role:add"
    }
  ],
  "system/role/generatedPermissionActions": [
    {
      "action": "bind",
      "label": "绑定",
      "legacy": "resources:gameGroup:bind"
    },
    {
      "action": "save",
      "label": "保存",
      "legacy": "depositWithdrawFee:setting:save"
    },
    {
      "action": "remark",
      "label": "备注",
      "legacy": "funds:deposit:remark"
    },
    {
      "action": "edit",
      "label": "编辑",
      "legacy": "activity:manage:edit"
    },
    {
      "action": "edit",
      "label": "编辑",
      "legacy": "depositWithdrawFee:template:edit"
    },
    {
      "action": "edit",
      "label": "编辑",
      "legacy": "funds:nexusAddress:edit"
    },
    {
      "action": "edit",
      "label": "编辑",
      "legacy": "funds:operationExpense:edit"
    },
    {
      "action": "edit",
      "label": "编辑",
      "legacy": "funds:redpacket:edit"
    },
    {
      "action": "edit",
      "label": "编辑",
      "legacy": "game:config:edit"
    },
    {
      "action": "edit",
      "label": "编辑",
      "legacy": "game:site:edit"
    },
    {
      "action": "edit",
      "label": "编辑",
      "legacy": "game:siteResource:edit"
    },
    {
      "action": "edit",
      "label": "编辑",
      "legacy": "member:agent:edit"
    },
    {
      "action": "edit",
      "label": "编辑",
      "legacy": "member:promotion:edit"
    },
    {
      "action": "edit",
      "label": "编辑",
      "legacy": "member:team:edit"
    },
    {
      "action": "edit",
      "label": "编辑",
      "legacy": "member:user:edit"
    },
    {
      "action": "edit",
      "label": "编辑",
      "legacy": "module:rebate:edit"
    },
    {
      "action": "edit",
      "label": "编辑",
      "legacy": "monitor:job:edit"
    },
    {
      "action": "edit",
      "label": "编辑",
      "legacy": "resources:appVersion:edit"
    },
    {
      "action": "edit",
      "label": "编辑",
      "legacy": "resources:areaCode:edit"
    },
    {
      "action": "edit",
      "label": "编辑",
      "legacy": "resources:gameBase:edit"
    },
    {
      "action": "edit",
      "label": "编辑",
      "legacy": "resources:gameCurrency:edit"
    },
    {
      "action": "edit",
      "label": "编辑",
      "legacy": "resources:gameFactory:edit"
    },
    {
      "action": "edit",
      "label": "编辑",
      "legacy": "resources:gameGroup:edit"
    },
    {
      "action": "edit",
      "label": "编辑",
      "legacy": "resources:gameLine:edit"
    },
    {
      "action": "edit",
      "label": "编辑",
      "legacy": "resources:realNameChannel:edit"
    },
    {
      "action": "edit",
      "label": "编辑",
      "legacy": "resources:skin:edit"
    },
    {
      "action": "edit",
      "label": "编辑",
      "legacy": "resources:smsChannel:edit"
    },
    {
      "action": "edit",
      "label": "编辑",
      "legacy": "system:account:edit"
    },
    {
      "action": "edit",
      "label": "编辑",
      "legacy": "system:commission:edit"
    },
    {
      "action": "edit",
      "label": "编辑",
      "legacy": "system:config:edit"
    },
    {
      "action": "edit",
      "label": "编辑",
      "legacy": "system:dept:edit"
    },
    {
      "action": "edit",
      "label": "编辑",
      "legacy": "system:dict:edit"
    },
    {
      "action": "edit",
      "label": "编辑",
      "legacy": "system:game:edit"
    },
    {
      "action": "edit",
      "label": "编辑",
      "legacy": "system:menu:edit"
    },
    {
      "action": "edit",
      "label": "编辑",
      "legacy": "system:message:edit"
    },
    {
      "action": "edit",
      "label": "编辑",
      "legacy": "system:messageTemplate:edit"
    },
    {
      "action": "edit",
      "label": "编辑",
      "legacy": "system:notice:edit"
    },
    {
      "action": "edit",
      "label": "编辑",
      "legacy": "system:post:edit"
    },
    {
      "action": "edit",
      "label": "编辑",
      "legacy": "system:role:edit"
    },
    {
      "action": "edit",
      "label": "编辑",
      "legacy": "system:skin:edit"
    },
    {
      "action": "edit",
      "label": "编辑",
      "legacy": "system:user:edit"
    },
    {
      "action": "edit",
      "label": "编辑",
      "legacy": "system:venue:edit"
    },
    {
      "action": "edit",
      "label": "编辑",
      "legacy": "telegram:config:edit"
    },
    {
      "action": "edit",
      "label": "编辑",
      "legacy": "tool:gen:edit"
    },
    {
      "action": "edit",
      "label": "编辑",
      "legacy": "turnover:config:edit"
    },
    {
      "action": "edit",
      "label": "编辑",
      "legacy": "turnover:withdraw:edit"
    },
    {
      "action": "edit",
      "label": "编辑",
      "legacy": "venue:feeConfig:edit"
    },
    {
      "action": "edit",
      "label": "编辑",
      "legacy": "venue:feeDetail:edit"
    },
    {
      "action": "recharge",
      "label": "补充额度",
      "legacy": "funds:mainBalance:recharge"
    },
    {
      "action": "query",
      "label": "查看",
      "legacy": "bet:records:query"
    },
    {
      "action": "query",
      "label": "查看",
      "legacy": "funds:deposit:query"
    },
    {
      "action": "view",
      "label": "查看",
      "legacy": "funds:deposit:view"
    },
    {
      "action": "query",
      "label": "查看",
      "legacy": "funds:nexusAddress:query"
    },
    {
      "action": "view",
      "label": "查看",
      "legacy": "funds:record:view"
    },
    {
      "action": "view",
      "label": "查看",
      "legacy": "funds:withdraw:view"
    },
    {
      "action": "list",
      "label": "查看",
      "legacy": "game:config:list"
    },
    {
      "action": "query",
      "label": "查看",
      "legacy": "game:site:publish:query"
    },
    {
      "action": "query",
      "label": "查看",
      "legacy": "game:site:query"
    },
    {
      "action": "query",
      "label": "查看",
      "legacy": "member:agent:query"
    },
    {
      "action": "query",
      "label": "查看",
      "legacy": "member:sameIp:query"
    },
    {
      "action": "query",
      "label": "查看",
      "legacy": "monitor:job:query"
    },
    {
      "action": "query",
      "label": "查看",
      "legacy": "monitor:operlog:query"
    },
    {
      "action": "query",
      "label": "查看",
      "legacy": "resources:gameAutoDisableLog:query"
    },
    {
      "action": "query",
      "label": "查看",
      "legacy": "system:feedback:query"
    },
    {
      "action": "query",
      "label": "查看",
      "legacy": "system:message:query"
    },
    {
      "action": "list",
      "label": "查看",
      "legacy": "system:user:list"
    },
    {
      "action": "detail",
      "label": "查看详情",
      "legacy": "system:gameBet:detail"
    },
    {
      "action": "recall",
      "label": "撤回",
      "legacy": "system:message:recall"
    },
    {
      "action": "export",
      "label": "导出",
      "legacy": "agent:commission:export"
    },
    {
      "action": "export",
      "label": "导出",
      "legacy": "agent:reversalRepayment:export"
    },
    {
      "action": "export",
      "label": "导出",
      "legacy": "agent:reversalStats:export"
    },
    {
      "action": "export",
      "label": "导出",
      "legacy": "bet:records:export"
    },
    {
      "action": "export",
      "label": "导出",
      "legacy": "depositWithdrawFee:report:export"
    },
    {
      "action": "export",
      "label": "导出",
      "legacy": "funds:depositWithdrawRecord:export"
    },
    {
      "action": "export",
      "label": "导出",
      "legacy": "funds:mainBalance:export"
    },
    {
      "action": "export",
      "label": "导出",
      "legacy": "funds:quotaAdjustment:export"
    },
    {
      "action": "export",
      "label": "导出",
      "legacy": "funds:record:export"
    },
    {
      "action": "export",
      "label": "导出",
      "legacy": "funds:redpacket:export"
    },
    {
      "action": "export",
      "label": "导出",
      "legacy": "game:report:export"
    },
    {
      "action": "export",
      "label": "导出",
      "legacy": "game:site:export"
    },
    {
      "action": "export",
      "label": "导出",
      "legacy": "member:agent:export"
    },
    {
      "action": "export",
      "label": "导出",
      "legacy": "monitor:job:export"
    },
    {
      "action": "export",
      "label": "导出",
      "legacy": "monitor:logininfor:export"
    },
    {
      "action": "export",
      "label": "导出",
      "legacy": "monitor:operlog:export"
    },
    {
      "action": "export",
      "label": "导出",
      "legacy": "resources:gameAutoDisableLog:export"
    },
    {
      "action": "export",
      "label": "导出",
      "legacy": "system:agent:export"
    },
    {
      "action": "export",
      "label": "导出",
      "legacy": "system:config:export"
    },
    {
      "action": "export",
      "label": "导出",
      "legacy": "system:dict:export"
    },
    {
      "action": "export",
      "label": "导出",
      "legacy": "system:feedback:export"
    },
    {
      "action": "export",
      "label": "导出",
      "legacy": "system:gameBet:export"
    },
    {
      "action": "export",
      "label": "导出",
      "legacy": "system:message:export"
    },
    {
      "action": "export",
      "label": "导出",
      "legacy": "system:post:export"
    },
    {
      "action": "export",
      "label": "导出",
      "legacy": "system:role:export"
    },
    {
      "action": "export",
      "label": "导出",
      "legacy": "system:user:export"
    },
    {
      "action": "export",
      "label": "导出",
      "legacy": "telegram:config:export"
    },
    {
      "action": "export",
      "label": "导出",
      "legacy": "venue:agentFeeDetail:export"
    },
    {
      "action": "export",
      "label": "导出",
      "legacy": "venue:feeDetail:export"
    },
    {
      "action": "export",
      "label": "导出",
      "legacy": "vip:bonus:export"
    },
    {
      "action": "export",
      "label": "导出",
      "legacy": "vip:rebate:export"
    },
    {
      "action": "import",
      "label": "导入",
      "legacy": "funds:nexusAddress:import"
    },
    {
      "action": "import",
      "label": "导入",
      "legacy": "system:user:import"
    },
    {
      "action": "import",
      "label": "导入",
      "legacy": "tool:gen:import"
    },
    {
      "action": "adjust",
      "label": "调整余额",
      "legacy": "funds:quotaAdjustment:adjust"
    },
    {
      "action": "grant",
      "label": "发放",
      "legacy": "agent:commission:grant"
    },
    {
      "action": "activityCash",
      "label": "发活动彩金",
      "legacy": "funds:mainBalance:activityCash"
    },
    {
      "action": "send",
      "label": "发送",
      "legacy": "system:message:send"
    },
    {
      "action": "googleAuth",
      "label": "谷歌验证",
      "legacy": "system:user:googleAuth"
    },
    {
      "action": "unlock",
      "label": "解锁",
      "legacy": "monitor:logininfor:unlock"
    },
    {
      "action": "config",
      "label": "配置",
      "legacy": "game:site:config"
    },
    {
      "action": "changeStatus",
      "label": "启用/禁用",
      "legacy": "monitor:job:changeStatus"
    },
    {
      "action": "forceLogout",
      "label": "强制退出",
      "legacy": "monitor:online:forceLogout"
    },
    {
      "action": "remove",
      "label": "删除",
      "legacy": "bet:records:remove"
    },
    {
      "action": "remove",
      "label": "删除",
      "legacy": "depositWithdrawFee:template:remove"
    },
    {
      "action": "remove",
      "label": "删除",
      "legacy": "funds:nexusAddress:remove"
    },
    {
      "action": "remove",
      "label": "删除",
      "legacy": "game:config:remove"
    },
    {
      "action": "remove",
      "label": "删除",
      "legacy": "game:site:publish:remove"
    },
    {
      "action": "remove",
      "label": "删除",
      "legacy": "game:site:remove"
    },
    {
      "action": "remove",
      "label": "删除",
      "legacy": "game:siteResource:remove"
    },
    {
      "action": "remove",
      "label": "删除",
      "legacy": "member:agent:remove"
    },
    {
      "action": "remove",
      "label": "删除",
      "legacy": "member:team:remove"
    },
    {
      "action": "remove",
      "label": "删除",
      "legacy": "member:user:remove"
    },
    {
      "action": "remove",
      "label": "删除",
      "legacy": "module:rebate:remove"
    },
    {
      "action": "remove",
      "label": "删除",
      "legacy": "monitor:job:remove"
    },
    {
      "action": "remove",
      "label": "删除",
      "legacy": "monitor:logininfor:remove"
    },
    {
      "action": "remove",
      "label": "删除",
      "legacy": "monitor:operlog:remove"
    },
    {
      "action": "remove",
      "label": "删除",
      "legacy": "resources:appVersion:remove"
    },
    {
      "action": "remove",
      "label": "删除",
      "legacy": "resources:areaCode:remove"
    },
    {
      "action": "remove",
      "label": "删除",
      "legacy": "resources:gameBase:remove"
    },
    {
      "action": "remove",
      "label": "删除",
      "legacy": "resources:gameCurrency:remove"
    },
    {
      "action": "remove",
      "label": "删除",
      "legacy": "resources:gameFactory:remove"
    },
    {
      "action": "remove",
      "label": "删除",
      "legacy": "resources:gameGroup:remove"
    },
    {
      "action": "remove",
      "label": "删除",
      "legacy": "resources:gameLine:remove"
    },
    {
      "action": "remove",
      "label": "删除",
      "legacy": "resources:realNameChannel:remove"
    },
    {
      "action": "remove",
      "label": "删除",
      "legacy": "resources:skin:remove"
    },
    {
      "action": "remove",
      "label": "删除",
      "legacy": "resources:smsChannel:remove"
    },
    {
      "action": "remove",
      "label": "删除",
      "legacy": "system:account:remove"
    },
    {
      "action": "remove",
      "label": "删除",
      "legacy": "system:commission:remove"
    },
    {
      "action": "remove",
      "label": "删除",
      "legacy": "system:config:remove"
    },
    {
      "action": "remove",
      "label": "删除",
      "legacy": "system:dept:remove"
    },
    {
      "action": "remove",
      "label": "删除",
      "legacy": "system:dict:remove"
    },
    {
      "action": "remove",
      "label": "删除",
      "legacy": "system:game:remove"
    },
    {
      "action": "remove",
      "label": "删除",
      "legacy": "system:menu:remove"
    },
    {
      "action": "remove",
      "label": "删除",
      "legacy": "system:message:remove"
    },
    {
      "action": "remove",
      "label": "删除",
      "legacy": "system:messageTemplate:remove"
    },
    {
      "action": "remove",
      "label": "删除",
      "legacy": "system:notice:remove"
    },
    {
      "action": "remove",
      "label": "删除",
      "legacy": "system:post:remove"
    },
    {
      "action": "remove",
      "label": "删除",
      "legacy": "system:role:remove"
    },
    {
      "action": "remove",
      "label": "删除",
      "legacy": "system:skin:remove"
    },
    {
      "action": "remove",
      "label": "删除",
      "legacy": "system:user:remove"
    },
    {
      "action": "remove",
      "label": "删除",
      "legacy": "system:venue:remove"
    },
    {
      "action": "remove",
      "label": "删除",
      "legacy": "telegram:config:remove"
    },
    {
      "action": "remove",
      "label": "删除",
      "legacy": "tool:gen:remove"
    },
    {
      "action": "apply",
      "label": "申请",
      "legacy": "game:site:apply"
    },
    {
      "action": "reject",
      "label": "审核拒绝",
      "legacy": "funds:deposit:reject"
    },
    {
      "action": "approve",
      "label": "审核通过",
      "legacy": "funds:deposit:approve"
    },
    {
      "action": "approve",
      "label": "审核通过",
      "legacy": "funds:withdraw:approve"
    },
    {
      "action": "approve",
      "label": "审核通过",
      "legacy": "game:site:approve"
    },
    {
      "action": "code",
      "label": "生成代码",
      "legacy": "tool:gen:code"
    },
    {
      "action": "release",
      "label": "释放",
      "legacy": "funds:nexusAddress:release"
    },
    {
      "action": "auth",
      "label": "授权",
      "legacy": "system:messageTemplate:auth"
    },
    {
      "action": "sync",
      "label": "同步",
      "legacy": "bet:records:sync"
    },
    {
      "action": "sync",
      "label": "同步",
      "legacy": "system:game:sync"
    },
    {
      "action": "complete",
      "label": "完成",
      "legacy": "funds:withdraw:complete"
    },
    {
      "action": "add",
      "label": "新增",
      "legacy": "activity:manage:add"
    },
    {
      "action": "add",
      "label": "新增",
      "legacy": "depositWithdrawFee:template:add"
    },
    {
      "action": "add",
      "label": "新增",
      "legacy": "funds:deposit:add"
    },
    {
      "action": "add",
      "label": "新增",
      "legacy": "funds:redpacket:add"
    },
    {
      "action": "add",
      "label": "新增",
      "legacy": "game:config:add"
    },
    {
      "action": "add",
      "label": "新增",
      "legacy": "game:site:add"
    },
    {
      "action": "add",
      "label": "新增",
      "legacy": "game:site:publish:add"
    },
    {
      "action": "add",
      "label": "新增",
      "legacy": "game:siteResource:add"
    },
    {
      "action": "add",
      "label": "新增",
      "legacy": "member:agent:add"
    },
    {
      "action": "add",
      "label": "新增",
      "legacy": "member:team:add"
    },
    {
      "action": "add",
      "label": "新增",
      "legacy": "member:user:add"
    },
    {
      "action": "add",
      "label": "新增",
      "legacy": "module:rebate:add"
    },
    {
      "action": "add",
      "label": "新增",
      "legacy": "monitor:job:add"
    },
    {
      "action": "add",
      "label": "新增",
      "legacy": "resources:appVersion:add"
    },
    {
      "action": "add",
      "label": "新增",
      "legacy": "resources:areaCode:add"
    },
    {
      "action": "add",
      "label": "新增",
      "legacy": "resources:gameBase:add"
    },
    {
      "action": "add",
      "label": "新增",
      "legacy": "resources:gameCurrency:add"
    },
    {
      "action": "add",
      "label": "新增",
      "legacy": "resources:gameFactory:add"
    },
    {
      "action": "add",
      "label": "新增",
      "legacy": "resources:gameGroup:add"
    },
    {
      "action": "add",
      "label": "新增",
      "legacy": "resources:gameLine:add"
    },
    {
      "action": "add",
      "label": "新增",
      "legacy": "resources:realNameChannel:add"
    },
    {
      "action": "add",
      "label": "新增",
      "legacy": "resources:skin:add"
    },
    {
      "action": "add",
      "label": "新增",
      "legacy": "resources:smsChannel:add"
    },
    {
      "action": "add",
      "label": "新增",
      "legacy": "system:account:add"
    },
    {
      "action": "add",
      "label": "新增",
      "legacy": "system:config:add"
    },
    {
      "action": "add",
      "label": "新增",
      "legacy": "system:dept:add"
    },
    {
      "action": "add",
      "label": "新增",
      "legacy": "system:dict:add"
    },
    {
      "action": "add",
      "label": "新增",
      "legacy": "system:game:add"
    },
    {
      "action": "add",
      "label": "新增",
      "legacy": "system:menu:add"
    },
    {
      "action": "add",
      "label": "新增",
      "legacy": "system:message:add"
    },
    {
      "action": "add",
      "label": "新增",
      "legacy": "system:messageTemplate:add"
    },
    {
      "action": "add",
      "label": "新增",
      "legacy": "system:notice:add"
    },
    {
      "action": "add",
      "label": "新增",
      "legacy": "system:post:add"
    },
    {
      "action": "add",
      "label": "新增",
      "legacy": "system:role:add"
    },
    {
      "action": "add",
      "label": "新增",
      "legacy": "system:user:add"
    },
    {
      "action": "add",
      "label": "新增",
      "legacy": "system:venue:add"
    },
    {
      "action": "add",
      "label": "新增",
      "legacy": "telegram:config:add"
    },
    {
      "action": "preview",
      "label": "预览",
      "legacy": "tool:gen:preview"
    },
    {
      "action": "resetPwd",
      "label": "重置密码",
      "legacy": "member:agent:resetPwd"
    },
    {
      "action": "resetPwd",
      "label": "重置密码",
      "legacy": "system:user:resetPwd"
    },
    {
      "action": "transfer",
      "label": "转账",
      "legacy": "funds:withdraw:transfer"
    },
    {
      "action": "reopen",
      "label": "reopen",
      "legacy": "system:feedback:reopen"
    },
    {
      "action": "reply",
      "label": "reply",
      "legacy": "system:feedback:reply"
    },
    {
      "action": "v2",
      "label": "v2",
      "legacy": "master-admin-prototype:withdraw-channel-settings:v2"
    },
    {
      "action": "v3",
      "label": "v3",
      "legacy": "master-admin-prototype:pay-channel-settings:v3"
    },
    {
      "action": "v4",
      "label": "v4",
      "legacy": "master-admin-prototype:drop-sign-analysis:v4"
    }
  ],
  "system/role/index": [
    {
      "action": "edit",
      "label": "编辑",
      "legacy": ""
    },
    {
      "action": "export",
      "label": "导出",
      "legacy": ""
    },
    {
      "action": "status",
      "label": "启用/禁用",
      "legacy": ""
    },
    {
      "action": "delete",
      "label": "删除",
      "legacy": ""
    },
    {
      "action": "create",
      "label": "新增",
      "legacy": ""
    }
  ],
  "system/user/index": [
    {
      "action": "edit",
      "label": "编辑",
      "legacy": "system:user:edit"
    },
    {
      "action": "export",
      "label": "导出",
      "legacy": "system:user:export"
    },
    {
      "action": "import",
      "label": "导入",
      "legacy": "system:user:import"
    },
    {
      "action": "remove",
      "label": "删除",
      "legacy": "system:user:remove"
    },
    {
      "action": "add",
      "label": "新增",
      "legacy": "system:user:add"
    },
    {
      "action": "resetPwd",
      "label": "重置密码",
      "legacy": "system:user:resetPwd"
    }
  ],
  "telegram/index": [
    {
      "action": "edit",
      "label": "编辑",
      "legacy": ""
    },
    {
      "action": "edit",
      "label": "编辑",
      "legacy": "telegram:config:edit"
    },
    {
      "action": "export",
      "label": "导出",
      "legacy": ""
    },
    {
      "action": "export",
      "label": "导出",
      "legacy": "telegram:config:export"
    },
    {
      "action": "delete",
      "label": "删除",
      "legacy": ""
    },
    {
      "action": "remove",
      "label": "删除",
      "legacy": "telegram:config:remove"
    },
    {
      "action": "create",
      "label": "新增",
      "legacy": ""
    },
    {
      "action": "add",
      "label": "新增",
      "legacy": "telegram:config:add"
    }
  ],
  "tool/build/index": [
    {
      "action": "export",
      "label": "导出",
      "legacy": ""
    }
  ],
  "tool/gen/index": [
    {
      "action": "edit",
      "label": "编辑",
      "legacy": ""
    },
    {
      "action": "edit",
      "label": "编辑",
      "legacy": "tool:gen:edit"
    },
    {
      "action": "import",
      "label": "导入",
      "legacy": ""
    },
    {
      "action": "import",
      "label": "导入",
      "legacy": "tool:gen:import"
    },
    {
      "action": "delete",
      "label": "删除",
      "legacy": ""
    },
    {
      "action": "remove",
      "label": "删除",
      "legacy": "tool:gen:remove"
    },
    {
      "action": "code",
      "label": "生成代码",
      "legacy": "tool:gen:code"
    },
    {
      "action": "sync",
      "label": "同步",
      "legacy": ""
    },
    {
      "action": "preview",
      "label": "预览",
      "legacy": "tool:gen:preview"
    }
  ],
  "venue/index": [
    {
      "action": "edit",
      "label": "编辑",
      "legacy": ""
    },
    {
      "action": "edit",
      "label": "编辑",
      "legacy": "system:venue:edit"
    },
    {
      "action": "delete",
      "label": "删除",
      "legacy": ""
    },
    {
      "action": "remove",
      "label": "删除",
      "legacy": "system:venue:remove"
    },
    {
      "action": "create",
      "label": "新增",
      "legacy": ""
    },
    {
      "action": "add",
      "label": "新增",
      "legacy": "system:venue:add"
    }
  ]
}
